(*
 * Generated by .Net DLL/WSDL Import Utility for Delphi
 *
 * Version:  6.0.6.0
 *
 * File generated on 22/02/2019 16:47:00 from .Net Library location below.
 *    .Net Library GAC Path: Microsoft.ReportViewer.WinForms
 *
 * Home: https://www.crystalnet-tech.com/RuntimeLibrary/RuntimeLibrary4Delphi
 *)

unit Microsoft.ReportViewer.WinForms.Enums;

{$WARN BOUNDS_ERROR OFF}

interface

uses
	{$IF CompilerVersion > 22}
	Winapi.ActiveX 
{$ELSE}
	ActiveX 
{$IFEND};

type
	PageCountMode = TOleEnum;
const
	PageCountMode_Actual = $00000000;
	PageCountMode_Estimate = $00000001;

type
	ExtensionTypeEnum = TOleEnum;
const
	ExtensionTypeEnum_Delivery = $00000000;
	ExtensionTypeEnum_Render = $00000001;
	ExtensionTypeEnum_Data = $00000002;
	ExtensionTypeEnum_All = $00000003;

type
	SoapProtocolVersion = TOleEnum;
const
	SoapProtocolVersion_Default = $00000000;
	SoapProtocolVersion_Soap11 = $00000001;
	SoapProtocolVersion_Soap12 = $00000002;

type
	SortDirectionEnum = TOleEnum;
const
	SortDirectionEnum_None = $00000000;
	SortDirectionEnum_Ascending = $00000001;
	SortDirectionEnum_Descending = $00000002;

type
	ParameterStateEnum = TOleEnum;
const
	ParameterStateEnum_HasValidValue = $00000000;
	ParameterStateEnum_MissingValidValue = $00000001;
	ParameterStateEnum_HasOutstandingDependencies = $00000002;
	ParameterStateEnum_DynamicValuesUnavailable = $00000003;

type
	ParameterTypeEnum = TOleEnum;
const
	ParameterTypeEnum_Boolean = $00000000;
	ParameterTypeEnum_DateTime = $00000001;
	ParameterTypeEnum_Integer = $00000002;
	ParameterTypeEnum_Float = $00000003;
	ParameterTypeEnum_String = $00000004;

type
	ParameterDataType = TOleEnum;
const
	ParameterDataType_Boolean = $00000000;
	ParameterDataType_DateTime = $00000001;
	ParameterDataType_Float = $00000002;
	ParameterDataType_Integer = $00000003;
	ParameterDataType_String = $00000004;

type
	ParameterState = TOleEnum;
const
	ParameterState_HasValidValue = $00000000;
	ParameterState_MissingValidValue = $00000001;
	ParameterState_HasOutstandingDependencies = $00000002;
	ParameterState_DynamicValuesUnavailable = $00000003;

type
	AccessibleRole = TOleEnum;
const
	AccessibleRole_None = $00000000;
	AccessibleRole_TitleBar = $00000001;
	AccessibleRole_MenuBar = $00000002;
	AccessibleRole_ScrollBar = $00000003;
	AccessibleRole_Grip = $00000004;
	AccessibleRole_Sound = $00000005;
	AccessibleRole_Cursor = $00000006;
	AccessibleRole_Caret = $00000007;
	AccessibleRole_Alert = $00000008;
	AccessibleRole_Window = $00000009;
	AccessibleRole_Client = $0000000A;
	AccessibleRole_MenuPopup = $0000000B;
	AccessibleRole_MenuItem = $0000000C;
	AccessibleRole_ToolTip = $0000000D;
	AccessibleRole_Application = $0000000E;
	AccessibleRole_Document = $0000000F;
	AccessibleRole_Pane = $00000010;
	AccessibleRole_Chart = $00000011;
	AccessibleRole_Dialog = $00000012;
	AccessibleRole_Border = $00000013;
	AccessibleRole_Grouping = $00000014;
	AccessibleRole_Separator = $00000015;
	AccessibleRole_ToolBar = $00000016;
	AccessibleRole_StatusBar = $00000017;
	AccessibleRole_Table = $00000018;
	AccessibleRole_ColumnHeader = $00000019;
	AccessibleRole_RowHeader = $0000001A;
	AccessibleRole_Column_0 = $0000001B;
	AccessibleRole_Row_0 = $0000001C;
	AccessibleRole_Cell = $0000001D;
	AccessibleRole_Link = $0000001E;
	AccessibleRole_HelpBalloon = $0000001F;
	AccessibleRole_Character = $00000020;
	AccessibleRole_List = $00000021;
	AccessibleRole_ListItem = $00000022;
	AccessibleRole_Outline = $00000023;
	AccessibleRole_OutlineItem = $00000024;
	AccessibleRole_PageTab = $00000025;
	AccessibleRole_PropertyPage = $00000026;
	AccessibleRole_Indicator = $00000027;
	AccessibleRole_Graphic = $00000028;
	AccessibleRole_StaticText = $00000029;
	AccessibleRole_Text = $0000002A;
	AccessibleRole_PushButton = $0000002B;
	AccessibleRole_CheckButton = $0000002C;
	AccessibleRole_RadioButton = $0000002D;
	AccessibleRole_ComboBox = $0000002E;
	AccessibleRole_DropList = $0000002F;
	AccessibleRole_ProgressBar = $00000030;
	AccessibleRole_Dial_0 = $00000031;
	AccessibleRole_HotkeyField = $00000032;
	AccessibleRole_Slider = $00000033;
	AccessibleRole_SpinButton = $00000034;
	AccessibleRole_Diagram = $00000035;
	AccessibleRole_Animation = $00000036;
	AccessibleRole_Equation = $00000037;
	AccessibleRole_ButtonDropDown = $00000038;
	AccessibleRole_ButtonMenu = $00000039;
	AccessibleRole_ButtonDropDownGrid = $0000003A;
	AccessibleRole_WhiteSpace = $0000003B;
	AccessibleRole_PageTabList = $0000003C;
	AccessibleRole_Clock = $0000003D;
	AccessibleRole_SplitButton = $0000003E;
	AccessibleRole_IpAddress = $0000003F;
	AccessibleRole_OutlineButton = $00000040;
	AccessibleRole_Default = $FFFFFFFF;

type
	AnchorStyles = TOleEnum;
const
	AnchorStyles_None = $00000000;
	AnchorStyles_Top = $00000001;
	AnchorStyles_Bottom = $00000002;
	AnchorStyles_Left = $00000004;
	AnchorStyles_Right = $00000008;

type
	AutoScaleMode = TOleEnum;
const
	AutoScaleMode_None = $00000000;
	AutoScaleMode_Font = $00000001;
	AutoScaleMode_Dpi = $00000002;
	AutoScaleMode_Inherit = $00000003;

type
	AutoSizeMode = TOleEnum;
const
	AutoSizeMode_GrowAndShrink = $00000000;
	AutoSizeMode_GrowOnly = $00000001;

type
	AutoValidate = TOleEnum;
const
	AutoValidate_Disable = $00000000;
	AutoValidate_EnablePreventFocusChange = $00000001;
	AutoValidate_EnableAllowFocusChange = $00000002;
	AutoValidate_Inherit = $FFFFFFFF;

type
	ImageLayout = TOleEnum;
const
	ImageLayout_None = $00000000;
	ImageLayout_Tile = $00000001;
	ImageLayout_Center = $00000002;
	ImageLayout_Stretch = $00000003;
	ImageLayout_Zoom = $00000004;

type
	BorderStyle = TOleEnum;
const
	BorderStyle_None = $00000000;
	BorderStyle_FixedSingle = $00000001;
	BorderStyle_Fixed3D = $00000002;

type
	DisplayMode = TOleEnum;
const
	DisplayMode_Normal = $00000000;
	DisplayMode_PrintLayout = $00000001;

type
	DockStyle = TOleEnum;
const
	DockStyle_None = $00000000;
	DockStyle_Top = $00000001;
	DockStyle_Bottom = $00000002;
	DockStyle_Left = $00000003;
	DockStyle_Right = $00000004;
	DockStyle_Fill = $00000005;

type
	ImeMode = TOleEnum;
const
	ImeMode_NoControl = $00000000;
	ImeMode_On = $00000001;
	ImeMode_Off = $00000002;
	ImeMode_Disable = $00000003;
	ImeMode_Hiragana = $00000004;
	ImeMode_Katakana = $00000005;
	ImeMode_KatakanaHalf = $00000006;
	ImeMode_AlphaFull = $00000007;
	ImeMode_Alpha_0 = $00000008;
	ImeMode_HangulFull = $00000009;
	ImeMode_Hangul_0 = $0000000A;
	ImeMode_Close = $0000000B;
	ImeMode_OnHalf = $0000000C;
	ImeMode_Inherit = $FFFFFFFF;

type
	ProcessingMode = TOleEnum;
const
	ProcessingMode_Local = $00000000;
	ProcessingMode_Remote = $00000001;

type
	RightToLeft = TOleEnum;
const
	RightToLeft_No = $00000000;
	RightToLeft_Yes = $00000001;
	RightToLeft_Inherit = $00000002;

type
	ZoomMode = TOleEnum;
const
	ZoomMode_FullPage = $00000000;
	ZoomMode_PageWidth = $00000001;
	ZoomMode_Percent = $00000002;

type
	DragDropEffects = TOleEnum;
const
	DragDropEffects_None = $00000000;
	DragDropEffects_Copy = $00000001;
	DragDropEffects_Move = $00000002;
	DragDropEffects_Link = $00000004;
	DragDropEffects_Scroll = $80000000;
	DragDropEffects_All = $80000003;

type
	DialogResult = TOleEnum;
const
	DialogResult_None = $00000000;
	DialogResult_OK = $00000001;
	DialogResult_Cancel = $00000002;
	DialogResult_Abort = $00000003;
	DialogResult_Retry = $00000004;
	DialogResult_Ignore = $00000005;
	DialogResult_Yes = $00000006;
	DialogResult_No_0 = $00000007;

type
	GetChildAtPointSkip = TOleEnum;
const
	GetChildAtPointSkip_None = $00000000;
	GetChildAtPointSkip_Invisible = $00000001;
	GetChildAtPointSkip_Disabled = $00000002;
	GetChildAtPointSkip_Transparent = $00000004;

type
	PreProcessControlState = TOleEnum;
const
	PreProcessControlState_MessageProcessed = $00000000;
	PreProcessControlState_MessageNeeded = $00000001;
	PreProcessControlState_MessageNotNeeded = $00000002;

type
	BoundsSpecified = TOleEnum;
const
	BoundsSpecified_None = $00000000;
	BoundsSpecified_X = $00000001;
	BoundsSpecified_Y = $00000002;
	BoundsSpecified_Location = $00000003;
	BoundsSpecified_Width = $00000004;
	BoundsSpecified_Height = $00000008;
	BoundsSpecified_Size = $0000000C;
	BoundsSpecified_All = $0000000F;

type
	ValidationConstraints = TOleEnum;
const
	ValidationConstraints_None = $00000000;
	ValidationConstraints_Selectable = $00000001;
	ValidationConstraints_Enabled = $00000002;
	ValidationConstraints_Visible = $00000004;
	ValidationConstraints_TabStop = $00000008;
	ValidationConstraints_ImmediateChildren = $00000010;

type
	SortOrder = TOleEnum;
const
	SortOrder_Ascending = $00000000;
	SortOrder_Descending = $00000001;

type
	Severity = TOleEnum;
const
	Severity_Warning = $00000000;
	Severity_Error = $00000001;

type
	TPageCountMode = 
	(
		pcmActual, 
		pcmEstimate
	);

	TExtensionTypeEnum = 
	(
		eteDelivery, 
		eteRender, 
		eteData, 
		eteAll
	);

	TSoapProtocolVersion = 
	(
		spvDefault, 
		spvSoap11, 
		spvSoap12
	);

	TSortDirectionEnum = 
	(
		sdeNone, 
		sdeAscending, 
		sdeDescending
	);

	TParameterStateEnum = 
	(
		pseHasValidValue, 
		pseMissingValidValue, 
		pseHasOutstandingDependencies, 
		pseDynamicValuesUnavailable
	);

	TParameterTypeEnum = 
	(
		pteBoolean, 
		pteDateTime, 
		pteInteger, 
		pteFloat, 
		pteString
	);

	TParameterDataType = 
	(
		pdtBoolean, 
		pdtDateTime, 
		pdtFloat, 
		pdtInteger, 
		pdtString
	);

	TParameterState = 
	(
		psHasValidValue, 
		psMissingValidValue, 
		psHasOutstandingDependencies, 
		psDynamicValuesUnavailable
	);

	TAccessibleRole = 
	(
		arNone, 
		arTitleBar, 
		arMenuBar, 
		arScrollBar, 
		arGrip, 
		arSound, 
		arCursor, 
		arCaret, 
		arAlert, 
		arWindow, 
		arClient, 
		arMenuPopup, 
		arMenuItem, 
		arToolTip, 
		arApplication, 
		arDocument, 
		arPane, 
		arChart, 
		arDialog, 
		arBorder, 
		arGrouping, 
		arSeparator, 
		arToolBar, 
		arStatusBar, 
		arTable, 
		arColumnHeader, 
		arRowHeader, 
		arColumn_0, 
		arRow_0, 
		arCell, 
		arLink, 
		arHelpBalloon, 
		arCharacter, 
		arList, 
		arListItem, 
		arOutline, 
		arOutlineItem, 
		arPageTab, 
		arPropertyPage, 
		arIndicator, 
		arGraphic, 
		arStaticText, 
		arText, 
		arPushButton, 
		arCheckButton, 
		arRadioButton, 
		arComboBox, 
		arDropList, 
		arProgressBar, 
		arDial_0, 
		arHotkeyField, 
		arSlider, 
		arSpinButton, 
		arDiagram, 
		arAnimation, 
		arEquation, 
		arButtonDropDown, 
		arButtonMenu, 
		arButtonDropDownGrid, 
		arWhiteSpace, 
		arPageTabList, 
		arClock, 
		arSplitButton, 
		arIpAddress, 
		arOutlineButton, 
		arDefault
	);

	TAnchorStyles = 
	(
		asNone, 
		asTop, 
		asBottom, 
		asLeft, 
		asRight
	);
	TAnchorStyles_Set = Set of TAnchorStyles;

	TAutoScaleMode = 
	(
		asmNone, 
		asmFont, 
		asmDpi, 
		asmInherit
	);

	TAutoSizeMode = 
	(
		asmGrowAndShrink, 
		asmGrowOnly
	);

	TAutoValidate = 
	(
		avDisable, 
		avEnablePreventFocusChange, 
		avEnableAllowFocusChange, 
		avInherit
	);

	TImageLayout = 
	(
		ilNone, 
		ilTile, 
		ilCenter, 
		ilStretch, 
		ilZoom
	);

	TBorderStyle = 
	(
		bsNone, 
		bsFixedSingle, 
		bsFixed3D
	);

	TDisplayMode = 
	(
		dmNormal, 
		dmPrintLayout
	);

	TDockStyle = 
	(
		dsNone, 
		dsTop, 
		dsBottom, 
		dsLeft, 
		dsRight, 
		dsFill
	);

	TImeMode = 
	(
		imNoControl, 
		imOn, 
		imOff, 
		imDisable, 
		imHiragana, 
		imKatakana, 
		imKatakanaHalf, 
		imAlphaFull, 
		imAlpha_0, 
		imHangulFull, 
		imHangul_0, 
		imClose, 
		imOnHalf, 
		imInherit
	);

	TProcessingMode = 
	(
		pmLocal, 
		pmRemote
	);

	TRightToLeft = 
	(
		rtlNo, 
		rtlYes, 
		rtlInherit
	);

	TZoomMode = 
	(
		zmFullPage, 
		zmPageWidth, 
		zmPercent
	);

	TDragDropEffects = 
	(
		ddeNone, 
		ddeCopy, 
		ddeMove, 
		ddeLink, 
		ddeScroll, 
		ddeAll
	);
	TDragDropEffects_Set = Set of TDragDropEffects;

	TDialogResult = 
	(
		drNone, 
		drOK, 
		drCancel, 
		drAbort, 
		drRetry, 
		drIgnore, 
		drYes, 
		drNo_0
	);

	TGetChildAtPointSkip = 
	(
		gcapsNone, 
		gcapsInvisible, 
		gcapsDisabled, 
		gcapsTransparent
	);
	TGetChildAtPointSkip_Set = Set of TGetChildAtPointSkip;

	TPreProcessControlState = 
	(
		ppcsMessageProcessed, 
		ppcsMessageNeeded, 
		ppcsMessageNotNeeded
	);

	TBoundsSpecified = 
	(
		bsBoundsSpecified_1None, 
		bsX, 
		bsY, 
		bsLocation, 
		bsWidth, 
		bsHeight, 
		bsSize, 
		bsAll
	);
	TBoundsSpecified_Set = Set of TBoundsSpecified;

	TValidationConstraints = 
	(
		vcNone, 
		vcSelectable, 
		vcEnabled, 
		vcVisible, 
		vcTabStop, 
		vcImmediateChildren
	);
	TValidationConstraints_Set = Set of TValidationConstraints;

	TSortOrder = 
	(
		soAscending, 
		soDescending
	);

	TSeverity = 
	(
		severityWarning, 
		severityError
	);

const

	PageCountModeValues: array[TPageCountMode] of TOleEnum =
	(
		PageCountMode_Actual, 
		PageCountMode_Estimate
	);

	ExtensionTypeEnumValues: array[TExtensionTypeEnum] of TOleEnum =
	(
		ExtensionTypeEnum_Delivery, 
		ExtensionTypeEnum_Render, 
		ExtensionTypeEnum_Data, 
		ExtensionTypeEnum_All
	);

	SoapProtocolVersionValues: array[TSoapProtocolVersion] of TOleEnum =
	(
		SoapProtocolVersion_Default, 
		SoapProtocolVersion_Soap11, 
		SoapProtocolVersion_Soap12
	);

	SortDirectionEnumValues: array[TSortDirectionEnum] of TOleEnum =
	(
		SortDirectionEnum_None, 
		SortDirectionEnum_Ascending, 
		SortDirectionEnum_Descending
	);

	ParameterStateEnumValues: array[TParameterStateEnum] of TOleEnum =
	(
		ParameterStateEnum_HasValidValue, 
		ParameterStateEnum_MissingValidValue, 
		ParameterStateEnum_HasOutstandingDependencies, 
		ParameterStateEnum_DynamicValuesUnavailable
	);

	ParameterTypeEnumValues: array[TParameterTypeEnum] of TOleEnum =
	(
		ParameterTypeEnum_Boolean, 
		ParameterTypeEnum_DateTime, 
		ParameterTypeEnum_Integer, 
		ParameterTypeEnum_Float, 
		ParameterTypeEnum_String
	);

	ParameterDataTypeValues: array[TParameterDataType] of TOleEnum =
	(
		ParameterDataType_Boolean, 
		ParameterDataType_DateTime, 
		ParameterDataType_Float, 
		ParameterDataType_Integer, 
		ParameterDataType_String
	);

	ParameterStateValues: array[TParameterState] of TOleEnum =
	(
		ParameterState_HasValidValue, 
		ParameterState_MissingValidValue, 
		ParameterState_HasOutstandingDependencies, 
		ParameterState_DynamicValuesUnavailable
	);

	AccessibleRoleValues: array[TAccessibleRole] of TOleEnum =
	(
		AccessibleRole_None, 
		AccessibleRole_TitleBar, 
		AccessibleRole_MenuBar, 
		AccessibleRole_ScrollBar, 
		AccessibleRole_Grip, 
		AccessibleRole_Sound, 
		AccessibleRole_Cursor, 
		AccessibleRole_Caret, 
		AccessibleRole_Alert, 
		AccessibleRole_Window, 
		AccessibleRole_Client, 
		AccessibleRole_MenuPopup, 
		AccessibleRole_MenuItem, 
		AccessibleRole_ToolTip, 
		AccessibleRole_Application, 
		AccessibleRole_Document, 
		AccessibleRole_Pane, 
		AccessibleRole_Chart, 
		AccessibleRole_Dialog, 
		AccessibleRole_Border, 
		AccessibleRole_Grouping, 
		AccessibleRole_Separator, 
		AccessibleRole_ToolBar, 
		AccessibleRole_StatusBar, 
		AccessibleRole_Table, 
		AccessibleRole_ColumnHeader, 
		AccessibleRole_RowHeader, 
		AccessibleRole_Column_0, 
		AccessibleRole_Row_0, 
		AccessibleRole_Cell, 
		AccessibleRole_Link, 
		AccessibleRole_HelpBalloon, 
		AccessibleRole_Character, 
		AccessibleRole_List, 
		AccessibleRole_ListItem, 
		AccessibleRole_Outline, 
		AccessibleRole_OutlineItem, 
		AccessibleRole_PageTab, 
		AccessibleRole_PropertyPage, 
		AccessibleRole_Indicator, 
		AccessibleRole_Graphic, 
		AccessibleRole_StaticText, 
		AccessibleRole_Text, 
		AccessibleRole_PushButton, 
		AccessibleRole_CheckButton, 
		AccessibleRole_RadioButton, 
		AccessibleRole_ComboBox, 
		AccessibleRole_DropList, 
		AccessibleRole_ProgressBar, 
		AccessibleRole_Dial_0, 
		AccessibleRole_HotkeyField, 
		AccessibleRole_Slider, 
		AccessibleRole_SpinButton, 
		AccessibleRole_Diagram, 
		AccessibleRole_Animation, 
		AccessibleRole_Equation, 
		AccessibleRole_ButtonDropDown, 
		AccessibleRole_ButtonMenu, 
		AccessibleRole_ButtonDropDownGrid, 
		AccessibleRole_WhiteSpace, 
		AccessibleRole_PageTabList, 
		AccessibleRole_Clock, 
		AccessibleRole_SplitButton, 
		AccessibleRole_IpAddress, 
		AccessibleRole_OutlineButton, 
		AccessibleRole_Default
	);

	AnchorStylesValues: array[TAnchorStyles] of TOleEnum =
	(
		AnchorStyles_None, 
		AnchorStyles_Top, 
		AnchorStyles_Bottom, 
		AnchorStyles_Left, 
		AnchorStyles_Right
	);

	AutoScaleModeValues: array[TAutoScaleMode] of TOleEnum =
	(
		AutoScaleMode_None, 
		AutoScaleMode_Font, 
		AutoScaleMode_Dpi, 
		AutoScaleMode_Inherit
	);

	AutoSizeModeValues: array[TAutoSizeMode] of TOleEnum =
	(
		AutoSizeMode_GrowAndShrink, 
		AutoSizeMode_GrowOnly
	);

	AutoValidateValues: array[TAutoValidate] of TOleEnum =
	(
		AutoValidate_Disable, 
		AutoValidate_EnablePreventFocusChange, 
		AutoValidate_EnableAllowFocusChange, 
		AutoValidate_Inherit
	);

	ImageLayoutValues: array[TImageLayout] of TOleEnum =
	(
		ImageLayout_None, 
		ImageLayout_Tile, 
		ImageLayout_Center, 
		ImageLayout_Stretch, 
		ImageLayout_Zoom
	);

	BorderStyleValues: array[TBorderStyle] of TOleEnum =
	(
		BorderStyle_None, 
		BorderStyle_FixedSingle, 
		BorderStyle_Fixed3D
	);

	DisplayModeValues: array[TDisplayMode] of TOleEnum =
	(
		DisplayMode_Normal, 
		DisplayMode_PrintLayout
	);

	DockStyleValues: array[TDockStyle] of TOleEnum =
	(
		DockStyle_None, 
		DockStyle_Top, 
		DockStyle_Bottom, 
		DockStyle_Left, 
		DockStyle_Right, 
		DockStyle_Fill
	);

	ImeModeValues: array[TImeMode] of TOleEnum =
	(
		ImeMode_NoControl, 
		ImeMode_On, 
		ImeMode_Off, 
		ImeMode_Disable, 
		ImeMode_Hiragana, 
		ImeMode_Katakana, 
		ImeMode_KatakanaHalf, 
		ImeMode_AlphaFull, 
		ImeMode_Alpha_0, 
		ImeMode_HangulFull, 
		ImeMode_Hangul_0, 
		ImeMode_Close, 
		ImeMode_OnHalf, 
		ImeMode_Inherit
	);

	ProcessingModeValues: array[TProcessingMode] of TOleEnum =
	(
		ProcessingMode_Local, 
		ProcessingMode_Remote
	);

	RightToLeftValues: array[TRightToLeft] of TOleEnum =
	(
		RightToLeft_No, 
		RightToLeft_Yes, 
		RightToLeft_Inherit
	);

	ZoomModeValues: array[TZoomMode] of TOleEnum =
	(
		ZoomMode_FullPage, 
		ZoomMode_PageWidth, 
		ZoomMode_Percent
	);

	DragDropEffectsValues: array[TDragDropEffects] of TOleEnum =
	(
		DragDropEffects_None, 
		DragDropEffects_Copy, 
		DragDropEffects_Move, 
		DragDropEffects_Link, 
		DragDropEffects_Scroll, 
		DragDropEffects_All
	);

	DialogResultValues: array[TDialogResult] of TOleEnum =
	(
		DialogResult_None, 
		DialogResult_OK, 
		DialogResult_Cancel, 
		DialogResult_Abort, 
		DialogResult_Retry, 
		DialogResult_Ignore, 
		DialogResult_Yes, 
		DialogResult_No_0
	);

	GetChildAtPointSkipValues: array[TGetChildAtPointSkip] of TOleEnum =
	(
		GetChildAtPointSkip_None, 
		GetChildAtPointSkip_Invisible, 
		GetChildAtPointSkip_Disabled, 
		GetChildAtPointSkip_Transparent
	);

	PreProcessControlStateValues: array[TPreProcessControlState] of TOleEnum =
	(
		PreProcessControlState_MessageProcessed, 
		PreProcessControlState_MessageNeeded, 
		PreProcessControlState_MessageNotNeeded
	);

	BoundsSpecifiedValues: array[TBoundsSpecified] of TOleEnum =
	(
		BoundsSpecified_None, 
		BoundsSpecified_X, 
		BoundsSpecified_Y, 
		BoundsSpecified_Location, 
		BoundsSpecified_Width, 
		BoundsSpecified_Height, 
		BoundsSpecified_Size, 
		BoundsSpecified_All
	);

	ValidationConstraintsValues: array[TValidationConstraints] of TOleEnum =
	(
		ValidationConstraints_None, 
		ValidationConstraints_Selectable, 
		ValidationConstraints_Enabled, 
		ValidationConstraints_Visible, 
		ValidationConstraints_TabStop, 
		ValidationConstraints_ImmediateChildren
	);

	SortOrderValues: array[TSortOrder] of TOleEnum =
	(
		SortOrder_Ascending, 
		SortOrder_Descending
	);

	SeverityValues: array[TSeverity] of TOleEnum =
	(
		Severity_Warning, 
		Severity_Error
	);



function ToOleEnum(Flags: TAnchorStyles_Set) : TOleEnum; Overload;
function ToOleEnum(Flags: TDragDropEffects_Set) : TOleEnum; Overload;
function ToOleEnum(Flags: TGetChildAtPointSkip_Set) : TOleEnum; Overload;
function ToOleEnum(Flags: TBoundsSpecified_Set) : TOleEnum; Overload;
function ToOleEnum(Flags: TValidationConstraints_Set) : TOleEnum; Overload;
function OleEnumAsAnchorStyles(AnchorStyles: TOleEnum) : TAnchorStyles_Set;
function OleEnumAsDragDropEffects(DragDropEffects: TOleEnum) : TDragDropEffects_Set;
function OleEnumAsGetChildAtPointSkip(GetChildAtPointSkip: TOleEnum) : TGetChildAtPointSkip_Set;
function OleEnumAsBoundsSpecified(BoundsSpecified: TOleEnum) : TBoundsSpecified_Set;
function OleEnumAsValidationConstraints(ValidationConstraints: TOleEnum) : TValidationConstraints_Set;

implementation

function ToOleEnum(Flags: TAnchorStyles_Set) : TOleEnum;
var
	oFlag: TAnchorStyles;
begin
	Result := $0000000;
	for oFlag:= Low(TAnchorStyles) to High(TAnchorStyles) do
		if oFlag in Flags then
			Result := Result or AnchorStylesValues[oFlag];
end;

function ToOleEnum(Flags: TDragDropEffects_Set) : TOleEnum;
var
	oFlag: TDragDropEffects;
begin
	Result := $0000000;
	for oFlag:= Low(TDragDropEffects) to High(TDragDropEffects) do
		if oFlag in Flags then
			Result := Result or DragDropEffectsValues[oFlag];
end;

function ToOleEnum(Flags: TGetChildAtPointSkip_Set) : TOleEnum;
var
	oFlag: TGetChildAtPointSkip;
begin
	Result := $0000000;
	for oFlag:= Low(TGetChildAtPointSkip) to High(TGetChildAtPointSkip) do
		if oFlag in Flags then
			Result := Result or GetChildAtPointSkipValues[oFlag];
end;

function ToOleEnum(Flags: TBoundsSpecified_Set) : TOleEnum;
var
	oFlag: TBoundsSpecified;
begin
	Result := $0000000;
	for oFlag:= Low(TBoundsSpecified) to High(TBoundsSpecified) do
		if oFlag in Flags then
			Result := Result or BoundsSpecifiedValues[oFlag];
end;

function ToOleEnum(Flags: TValidationConstraints_Set) : TOleEnum;
var
	oFlag: TValidationConstraints;
begin
	Result := $0000000;
	for oFlag:= Low(TValidationConstraints) to High(TValidationConstraints) do
		if oFlag in Flags then
			Result := Result or ValidationConstraintsValues[oFlag];
end;

function OleEnumAsAnchorStyles(AnchorStyles: TOleEnum) : TAnchorStyles_Set;
var
	oFlag: TAnchorStyles;
	oOrd : Integer;
begin
	Result:= [];
	oOrd := Ord(AnchorStyles);
	for oFlag:= Low(TAnchorStyles) to High(TAnchorStyles) do
		if oOrd and(1 shl ord(oFlag)) > 0 then Include(Result, oFlag);
end;
function OleEnumAsDragDropEffects(DragDropEffects: TOleEnum) : TDragDropEffects_Set;
var
	oFlag: TDragDropEffects;
	oOrd : Integer;
begin
	Result:= [];
	oOrd := Ord(DragDropEffects);
	for oFlag:= Low(TDragDropEffects) to High(TDragDropEffects) do
		if oOrd and(1 shl ord(oFlag)) > 0 then Include(Result, oFlag);
end;
function OleEnumAsGetChildAtPointSkip(GetChildAtPointSkip: TOleEnum) : TGetChildAtPointSkip_Set;
var
	oFlag: TGetChildAtPointSkip;
	oOrd : Integer;
begin
	Result:= [];
	oOrd := Ord(GetChildAtPointSkip);
	for oFlag:= Low(TGetChildAtPointSkip) to High(TGetChildAtPointSkip) do
		if oOrd and(1 shl ord(oFlag)) > 0 then Include(Result, oFlag);
end;
function OleEnumAsBoundsSpecified(BoundsSpecified: TOleEnum) : TBoundsSpecified_Set;
var
	oFlag: TBoundsSpecified;
	oOrd : Integer;
begin
	Result:= [];
	oOrd := Ord(BoundsSpecified);
	for oFlag:= Low(TBoundsSpecified) to High(TBoundsSpecified) do
		if oOrd and(1 shl ord(oFlag)) > 0 then Include(Result, oFlag);
end;
function OleEnumAsValidationConstraints(ValidationConstraints: TOleEnum) : TValidationConstraints_Set;
var
	oFlag: TValidationConstraints;
	oOrd : Integer;
begin
	Result:= [];
	oOrd := Ord(ValidationConstraints);
	for oFlag:= Low(TValidationConstraints) to High(TValidationConstraints) do
		if oOrd and(1 shl ord(oFlag)) > 0 then Include(Result, oFlag);
end;

end.

