(*
 * Generated by .Net DLL/WSDL Import Utility for Delphi
 * Version:  6.0.8.1 x32
 * Options:
 *    Import Type: Import .Net Assembly Library
 *    Output Directory: C:\Temp\Demo\Application_Domains_And_Assemblies\Load_External_DLL_With_ImportUtility
 *    Separate Larger generated delphi units into different units: Yes
 *    Optimize process: Yes
 *    Exclude public field members of the selected types: Yes
 *    Search and include type references in other assemblies to be imported: Yes
 *    Convert .Net Generics to its equivalent in Delphi: Yes
 *
 * File generated on 02/05/2025 09:16:02 from .Net Library location below.
 *    .Net Library Path: Mathematics.dll
 *
 * Home: https://www.crystalnet-tech.com/RuntimeLibrary/RuntimeLibrary4Delphi
 *)

unit Mathematics.Consts;

interface

const

	sC_Mathematics_Asm_ID = 'b108b08a-5a14-4d01-bc86-16d1cbb65e5a';
	sC_Mathematics_sC_AssemblyPath = 'Mathematics.dll';

	sC_Mat_Mathematics = 'Mathematics.Mathematics';
	sC_Sys_Boolean = 'System.Boolean';
	sC_Sys_Int32 = 'System.Int32';

// **** Delphi Type FullNames ****

	sD_TMathematics = 'Mathematics.TMathematics';

implementation
end.

