(*
 * Generated by .Net DLL/WSDL Import Utility for Delphi
 * Version:  6.0.8.1 x32
 * 
 * File generated on 02/05/2025 09:16:01 from .Net Library location below.
 *    .Net Library Path: 
 *
 * Home: https://www.crystalnet-tech.com/RuntimeLibrary/RuntimeLibrary4Delphi
 *)

unit Mathematics.Intf;


interface
uses
	CNClrLib.Host, CNClrLib.Core, CNClrLib.Host.Utils, Mathematics.Consts;

type

	[TypeMapping(sD_TMathematics, sC_Mat_Mathematics)]
	IMathematics = interface(IClrBase)
	['{A7FEDBBA-A0EB-44F5-9375-EA27C85EAF5C}']
		{ public }
		function Add(a: Integer; b: Integer): Integer;
		function Equal(a: Integer; b: Integer): Boolean;
		function Subtract(a: Integer; b: Integer): Integer;
	end;

implementation

end.

