(*
 * Generated by .Net DLL/WSDL Import Utility for Delphi
 * Version:  6.0.8.1 x32
 * 
 * File generated on 02/05/2025 09:16:02 from .Net Library location below.
 *    .Net Library Path: Mathematics.dll
 *
 * Home: https://www.crystalnet-tech.com/RuntimeLibrary/RuntimeLibrary4Delphi
 *)

unit Mathematics;


interface
uses
	CNClrLib.Host, CNClrLib.Core, CNClrLib.Host.Utils, Mathematics.Consts, Mathematics.Intf;

type

{	TMathematics	}

	TMathematics = Class(TClrBaseObject, IMathematics)
	public
		constructor Create(AIntf: _ClrObject); overload;
		constructor Create; overload;
		function Add(a: Integer; b: Integer): Integer;
		function Equal(a: Integer; b: Integer): Boolean;
		function Subtract(a: Integer; b: Integer): Integer;
	end;


function GetMathematicsAssembly: TClrAssembly;

implementation

function GetMathematicsAssembly: TClrAssembly;
begin
	Result := TClrAssembly.GetRegisterAssembly(sC_Mathematics_Asm_ID);
end;

{	TMathematics	}

constructor TMathematics.Create(AIntf: _ClrObject);
begin
	inherited Create(AIntf);
end;

constructor TMathematics.Create;
begin
	inherited Create(sC_Mat_Mathematics, nil)
end;

function TMathematics.Add(a: Integer; b: Integer): Integer;
begin
	Result := InvokeMethod('Add', [sC_Sys_Int32, sC_Sys_Int32], [a, b]);
end;

function TMathematics.Equal(a: Integer; b: Integer): Boolean;
begin
	Result := InvokeMethod('Equal', [sC_Sys_Int32, sC_Sys_Int32], [a, b]);
end;

function TMathematics.Subtract(a: Integer; b: Integer): Integer;
begin
	Result := InvokeMethod('Subtract', [sC_Sys_Int32, sC_Sys_Int32], [a, b]);
end;


initialization
	TClrAssembly.RegisterDLLAssembly(sC_Mathematics_Asm_ID, sC_Mathematics_sC_AssemblyPath, ltfileLocation, False);
end.

