(*
 * Generated by .Net DLL/WSDL Import Utility for Delphi
 *
 * Version:  6.0.5.1
 *
 * File generated on 09/11/2018 21:55:13 from .Net Library location below.
 *    .Net Library Path: C:\Users\Bismark\Downloads\HostWPFInVCLFormsDelphi\WPFInVCL\WPF_MyControls_CSharp\MyControls\MyControls\bin\Release
 *
 * Home: https://www.crystalnet-tech.com/RuntimeLibrary/RuntimeLibrary4Delphi
 *)

unit MyControls.Intf;

{$WARN SYMBOL_PLATFORM OFF}
{$WARN HIDING_MEMBER OFF}

interface
uses
	CNClrLib.Host, CNClrLib.Core, CNClrLib.Host.Utils, CNClrLib.Generic.Helper, 
	CNClrLib.Windows, CNClrLib.System, CNClrLib.Collections, MyControls.Consts, 
	MyControls.Enums;

type
{ Forward Declarations }

	IMyControlEventArgs = interface;
	IMyControl1 = interface;

	[TypeMapping(sD_TMouseEventArgs, sC_SysWinInp_MouseEventArgs)]
	IMouseEventArgs = interface(IClrBaseObject)
	end;

	[TypeMapping(sD_TTouchEventArgs, sC_SysWinInp_TouchEventArgs)]
	ITouchEventArgs = interface(IClrBaseObject)
	end;

	[TypeMapping(sD_TKeyEventArgs, sC_SysWinInp_KeyEventArgs)]
	IKeyEventArgs = interface(IClrBaseObject)
	end;

	[TypeMapping(sD_TManipulationBoundaryFeedbackEventArgs, sC_SysWinInp_ManipulationBoundaryFeedbackEventArgs)]
	IManipulationBoundaryFeedbackEventArgs = interface(IClrBaseObject)
	end;

	[TypeMapping(sD_TManipulationCompletedEventArgs, sC_SysWinInp_ManipulationCompletedEventArgs)]
	IManipulationCompletedEventArgs = interface(IClrBaseObject)
	end;

	[TypeMapping(sD_TManipulationDeltaEventArgs, sC_SysWinInp_ManipulationDeltaEventArgs)]
	IManipulationDeltaEventArgs = interface(IClrBaseObject)
	end;

	[TypeMapping(sD_TManipulationInertiaStartingEventArgs, sC_SysWinInp_ManipulationInertiaStartingEventArgs)]
	IManipulationInertiaStartingEventArgs = interface(IClrBaseObject)
	end;

	[TypeMapping(sD_TManipulationStartedEventArgs, sC_SysWinInp_ManipulationStartedEventArgs)]
	IManipulationStartedEventArgs = interface(IClrBaseObject)
	end;

	[TypeMapping(sD_TManipulationStartingEventArgs, sC_SysWinInp_ManipulationStartingEventArgs)]
	IManipulationStartingEventArgs = interface(IClrBaseObject)
	end;

	[TypeMapping(sD_TDataTransferEventArgs, sC_SysWinDat_DataTransferEventArgs)]
	IDataTransferEventArgs = interface(IClrBaseObject)
	end;

	[TypeMapping(sD_TBitmapEffect, sC_SysWinMedEff_BitmapEffect)]
	IBitmapEffect = interface(IClrBaseObject)
	end;

	[TypeMapping(sD_TBitmapEffectInput, sC_SysWinMedEff_BitmapEffectInput)]
	IBitmapEffectInput = interface(IClrBaseObject)
	end;

	[TypeMapping(sD_TColumnDefinitionCollection, sC_SysWinCon_ColumnDefinitionCollection)]
	IColumnDefinitionCollection = interface(IClrBaseObject)
	end;

	[TypeMapping(sD_TContextMenu, sC_SysWinCon_ContextMenu)]
	IContextMenu = interface(IClrBaseObject)
	end;

	[TypeMapping(sD_TCursor, sC_SysWinInp_Cursor)]
	ICursor = interface(IClrBaseObject)
	end;

	[TypeMapping(sD_TStyle, sC_SysWin_Style)]
	IStyle = interface(IClrBaseObject)
	end;

	[TypeMapping(sD_TSolidColorBrush, sC_SysWinMed_SolidColorBrush)]
	ISolidColorBrush = interface(IClrBaseObject)
	end;

	[TypeMapping(sD_TRowDefinitionCollection, sC_SysWinCon_RowDefinitionCollection)]
	IRowDefinitionCollection = interface(IClrBaseObject)
	end;

{	Event Handlers	}
	TContextMenuEventHandler = procedure(sender: IClrBaseObject; e: _ContextMenuEventArgs) of Object;
	TDependencyPropertyChangedEventHandler = procedure(sender: IClrBaseObject; e: _DependencyPropertyChangedEventArgs) of Object;
	TDragEventHandler = procedure(sender: IClrBaseObject; e: _DragEventArgs) of Object;
	TGiveFeedbackEventHandler = procedure(sender: IClrBaseObject; e: _GiveFeedbackEventArgs) of Object;
	TRoutedEventHandler = procedure(sender: IClrBaseObject; e: _RoutedEventArgs) of Object;
	TKeyboardFocusChangedEventHandler = procedure(sender: IClrBaseObject; e: _KeyboardFocusChangedEventArgs) of Object;
	TMouseEventHandler = procedure(sender: IClrBaseObject; e: IMouseEventArgs) of Object;
	TStylusEventHandler = procedure(sender: IClrBaseObject; e: _StylusEventArgs) of Object;
	TEventHandler = procedure(sender: IClrBaseObject; e: ITouchEventArgs) of Object;
	TEventHandler_1 = procedure(sender: IClrBaseObject; e: _EventArgs) of Object;
	TKeyEventHandler = procedure(sender: IClrBaseObject; e: IKeyEventArgs) of Object;
	TEventHandler_2 = procedure(sender: IClrBaseObject; e: IManipulationBoundaryFeedbackEventArgs) of Object;
	TEventHandler_3 = procedure(sender: IClrBaseObject; e: IManipulationCompletedEventArgs) of Object;
	TEventHandler_4 = procedure(sender: IClrBaseObject; e: IManipulationDeltaEventArgs) of Object;
	TEventHandler_5 = procedure(sender: IClrBaseObject; e: IManipulationInertiaStartingEventArgs) of Object;
	TEventHandler_6 = procedure(sender: IClrBaseObject; e: IManipulationStartedEventArgs) of Object;
	TEventHandler_7 = procedure(sender: IClrBaseObject; e: IManipulationStartingEventArgs) of Object;
	TMouseButtonEventHandler = procedure(sender: IClrBaseObject; e: _MouseButtonEventArgs) of Object;
	TMouseWheelEventHandler = procedure(sender: IClrBaseObject; e: _MouseWheelEventArgs) of Object;
	TMyControlEventHandler = procedure(sender: IClrBaseObject; args: IMyControlEventArgs) of Object;
	TQueryContinueDragEventHandler = procedure(sender: IClrBaseObject; e: _QueryContinueDragEventArgs) of Object;
	TStylusButtonEventHandler = procedure(sender: IClrBaseObject; e: _StylusButtonEventArgs) of Object;
	TStylusDownEventHandler = procedure(sender: IClrBaseObject; e: _StylusDownEventArgs) of Object;
	TStylusSystemGestureEventHandler = procedure(sender: IClrBaseObject; e: _StylusSystemGestureEventArgs) of Object;
	TTextCompositionEventHandler = procedure(sender: IClrBaseObject; e: _TextCompositionEventArgs) of Object;
	TQueryCursorEventHandler = procedure(sender: IClrBaseObject; e: _QueryCursorEventArgs) of Object;
	TRequestBringIntoViewEventHandler = procedure(sender: IClrBaseObject; e: _RequestBringIntoViewEventArgs) of Object;
	TSizeChangedEventHandler = procedure(sender: IClrBaseObject; e: _SizeChangedEventArgs) of Object;
	TEventHandler_8 = procedure(sender: IClrBaseObject; e: IDataTransferEventArgs) of Object;
	TToolTipEventHandler = procedure(sender: IClrBaseObject; e: _ToolTipEventArgs) of Object;


	[TypeMapping(sD_TMyControl1, sC_MyC_MyControl1)]
	IMyControl1 = interface
		{ private }
		function Get_ActualHeight: Double;
		function Get_ActualWidth: Double;
		function Get_AllowDrop: Boolean;
		procedure Set_AllowDrop(Value: Boolean);
		function Get_AreAnyTouchesCaptured: Boolean;
		function Get_AreAnyTouchesCapturedWithin: Boolean;
		function Get_AreAnyTouchesDirectlyOver: Boolean;
		function Get_AreAnyTouchesOver: Boolean;
		function Get_Background: _Brush;
		procedure Set_Background(Value: _Brush);
		function Get_BindingGroup: _BindingGroup;
		procedure Set_BindingGroup(Value: _BindingGroup);
		function Get_BitmapEffect: IBitmapEffect;
		procedure Set_BitmapEffect(Value: IBitmapEffect);
		function Get_BitmapEffectInput: IBitmapEffectInput;
		procedure Set_BitmapEffectInput(Value: IBitmapEffectInput);
		function Get_CacheMode: _CacheMode;
		procedure Set_CacheMode(Value: _CacheMode);
		function Get_Children: _UIElementCollection;
		function Get_Clip: _Geometry;
		procedure Set_Clip(Value: _Geometry);
		function Get_ClipToBounds: Boolean;
		procedure Set_ClipToBounds(Value: Boolean);
		function Get_ColumnDefinitions: IColumnDefinitionCollection;
		function Get_CommandBindings: _CommandBindingCollection;
		function Get_ContextMenu: IContextMenu;
		procedure Set_ContextMenu(Value: IContextMenu);
		function Get_Cursor: ICursor;
		procedure Set_Cursor(Value: ICursor);
		function Get_DataContext: Olevariant;
		procedure Set_DataContext(Value: Olevariant);
		function Get_DependencyObjectType: _DependencyObjectType;
		function Get_DesiredSize: _Size;
		function Get_Dispatcher: _Dispatcher;
		function Get_Effect: _Effect;
		procedure Set_Effect(Value: _Effect);
		function Get_FlowDirection: TFlowDirection;
		procedure Set_FlowDirection(Value: TFlowDirection);
		function Get_Focusable: Boolean;
		procedure Set_Focusable(Value: Boolean);
		function Get_FocusVisualStyle: IStyle;
		procedure Set_FocusVisualStyle(Value: IStyle);
		function Get_ForceCursor: Boolean;
		procedure Set_ForceCursor(Value: Boolean);
		function Get_HasAnimatedProperties: Boolean;
		function Get_HasLogicalOrientationPublic: Boolean;
		function Get_Height: Double;
		procedure Set_Height(Value: Double);
		function Get_HorizontalAlignment: THorizontalAlignment;
		procedure Set_HorizontalAlignment(Value: THorizontalAlignment);
		function Get_InputBindings: _InputBindingCollection;
		function Get_InputScope: _InputScope;
		procedure Set_InputScope(Value: _InputScope);
		function Get_IsArrangeValid: Boolean;
		function Get_IsEnabled: Boolean;
		procedure Set_IsEnabled(Value: Boolean);
		function Get_IsFocused: Boolean;
		function Get_IsHitTestVisible: Boolean;
		procedure Set_IsHitTestVisible(Value: Boolean);
		function Get_IsInitialized: Boolean;
		function Get_IsInputMethodEnabled: Boolean;
		function Get_IsItemsHost: Boolean;
		procedure Set_IsItemsHost(Value: Boolean);
		function Get_IsKeyboardFocused: Boolean;
		function Get_IsKeyboardFocusWithin: Boolean;
		function Get_IsLoaded: Boolean;
		function Get_IsManipulationEnabled: Boolean;
		procedure Set_IsManipulationEnabled(Value: Boolean);
		function Get_IsMeasureValid: Boolean;
		function Get_IsMouseCaptured: Boolean;
		function Get_IsMouseCaptureWithin: Boolean;
		function Get_IsMouseDirectlyOver: Boolean;
		function Get_IsMouseOver: Boolean;
		function Get_IsSealed: Boolean;
		function Get_IsStylusCaptured: Boolean;
		function Get_IsStylusCaptureWithin: Boolean;
		function Get_IsStylusDirectlyOver: Boolean;
		function Get_IsStylusOver: Boolean;
		function Get_IsVisible: Boolean;
		function Get_Language: _XmlLanguage;
		procedure Set_Language(Value: _XmlLanguage);
		function Get_LayoutTransform: _Transform;
		procedure Set_LayoutTransform(Value: _Transform);
		function Get_LogicalOrientationPublic: TOrientation;
		function Get_Margin: _Thickness;
		procedure Set_Margin(Value: _Thickness);
		function Get_MaxHeight: Double;
		procedure Set_MaxHeight(Value: Double);
		function Get_MaxWidth: Double;
		procedure Set_MaxWidth(Value: Double);
		function Get_MinHeight: Double;
		procedure Set_MinHeight(Value: Double);
		function Get_MinWidth: Double;
		procedure Set_MinWidth(Value: Double);
		function Get_MyControl_Background: ISolidColorBrush;
		procedure Set_MyControl_Background(Value: ISolidColorBrush);
		function Get_MyControl_FontFamily: _FontFamily;
		procedure Set_MyControl_FontFamily(Value: _FontFamily);
		function Get_MyControl_FontSize: Double;
		procedure Set_MyControl_FontSize(Value: Double);
		function Get_MyControl_FontStyle: _FontStyle;
		procedure Set_MyControl_FontStyle(Value: _FontStyle);
		function Get_MyControl_FontWeight: _FontWeight;
		procedure Set_MyControl_FontWeight(Value: _FontWeight);
		function Get_MyControl_Foreground: ISolidColorBrush;
		procedure Set_MyControl_Foreground(Value: ISolidColorBrush);
		function Get_Name: String;
		procedure Set_Name(Value: String);
		function Get_Opacity: Double;
		procedure Set_Opacity(Value: Double);
		function Get_OpacityMask: _Brush;
		procedure Set_OpacityMask(Value: _Brush);
		function Get_OverridesDefaultStyle: Boolean;
		procedure Set_OverridesDefaultStyle(Value: Boolean);
		function Get_Parent: _DependencyObject;
		function Get_PersistId: Integer;
		function Get_RenderSize: _Size;
		procedure Set_RenderSize(Value: _Size);
		function Get_RenderTransform: _Transform;
		procedure Set_RenderTransform(Value: _Transform);
		function Get_RenderTransformOrigin: _Point;
		procedure Set_RenderTransformOrigin(Value: _Point);
		function Get_Resources: _ResourceDictionary;
		procedure Set_Resources(Value: _ResourceDictionary);
		function Get_RowDefinitions: IRowDefinitionCollection;
		function Get_ShowGridLines: Boolean;
		procedure Set_ShowGridLines(Value: Boolean);
		function Get_SnapsToDevicePixels: Boolean;
		procedure Set_SnapsToDevicePixels(Value: Boolean);
		function Get_Style: IStyle;
		procedure Set_Style(Value: IStyle);
		function Get_Tag: Olevariant;
		procedure Set_Tag(Value: Olevariant);
		function Get_TemplatedParent: _DependencyObject;
		function Get_ToolTip: Olevariant;
		procedure Set_ToolTip(Value: Olevariant);
		function Get_TouchesCaptured: IList<_TouchDevice>;
		function Get_TouchesCapturedWithin: IList<_TouchDevice>;
		function Get_TouchesDirectlyOver: IList<_TouchDevice>;
		function Get_TouchesOver: IList<_TouchDevice>;
		function Get_Triggers: _TriggerCollection;
		function Get_Uid: String;
		procedure Set_Uid(Value: String);
		function Get_UseLayoutRounding: Boolean;
		procedure Set_UseLayoutRounding(Value: Boolean);
		function Get_VerticalAlignment: TVerticalAlignment;
		procedure Set_VerticalAlignment(Value: TVerticalAlignment);
		function Get_Visibility: TVisibility;
		procedure Set_Visibility(Value: TVisibility);
		function Get_Width: Double;
		procedure Set_Width(Value: Double);
		function Get_ContextMenuClosing : TContextMenuEventHandler;
		procedure Set_ContextMenuClosing(Value : TContextMenuEventHandler);
		function Get_ContextMenuOpening : TContextMenuEventHandler;
		procedure Set_ContextMenuOpening(Value : TContextMenuEventHandler);
		function Get_DataContextChanged : TDependencyPropertyChangedEventHandler;
		procedure Set_DataContextChanged(Value : TDependencyPropertyChangedEventHandler);
		function Get_DragEnter : TDragEventHandler;
		procedure Set_DragEnter(Value : TDragEventHandler);
		function Get_DragLeave : TDragEventHandler;
		procedure Set_DragLeave(Value : TDragEventHandler);
		function Get_DragOver : TDragEventHandler;
		procedure Set_DragOver(Value : TDragEventHandler);
		function Get_Drop : TDragEventHandler;
		procedure Set_Drop(Value : TDragEventHandler);
		function Get_FocusableChanged : TDependencyPropertyChangedEventHandler;
		procedure Set_FocusableChanged(Value : TDependencyPropertyChangedEventHandler);
		function Get_GiveFeedback : TGiveFeedbackEventHandler;
		procedure Set_GiveFeedback(Value : TGiveFeedbackEventHandler);
		function Get_GotFocus : TRoutedEventHandler;
		procedure Set_GotFocus(Value : TRoutedEventHandler);
		function Get_GotKeyboardFocus : TKeyboardFocusChangedEventHandler;
		procedure Set_GotKeyboardFocus(Value : TKeyboardFocusChangedEventHandler);
		function Get_GotMouseCapture : TMouseEventHandler;
		procedure Set_GotMouseCapture(Value : TMouseEventHandler);
		function Get_GotStylusCapture : TStylusEventHandler;
		procedure Set_GotStylusCapture(Value : TStylusEventHandler);
		function Get_GotTouchCapture : TEventHandler;
		procedure Set_GotTouchCapture(Value : TEventHandler);
		function Get_Initialized : TEventHandler_1;
		procedure Set_Initialized(Value : TEventHandler_1);
		function Get_IsEnabledChanged : TDependencyPropertyChangedEventHandler;
		procedure Set_IsEnabledChanged(Value : TDependencyPropertyChangedEventHandler);
		function Get_IsHitTestVisibleChanged : TDependencyPropertyChangedEventHandler;
		procedure Set_IsHitTestVisibleChanged(Value : TDependencyPropertyChangedEventHandler);
		function Get_IsKeyboardFocusedChanged : TDependencyPropertyChangedEventHandler;
		procedure Set_IsKeyboardFocusedChanged(Value : TDependencyPropertyChangedEventHandler);
		function Get_IsKeyboardFocusWithinChanged : TDependencyPropertyChangedEventHandler;
		procedure Set_IsKeyboardFocusWithinChanged(Value : TDependencyPropertyChangedEventHandler);
		function Get_IsMouseCapturedChanged : TDependencyPropertyChangedEventHandler;
		procedure Set_IsMouseCapturedChanged(Value : TDependencyPropertyChangedEventHandler);
		function Get_IsMouseCaptureWithinChanged : TDependencyPropertyChangedEventHandler;
		procedure Set_IsMouseCaptureWithinChanged(Value : TDependencyPropertyChangedEventHandler);
		function Get_IsMouseDirectlyOverChanged : TDependencyPropertyChangedEventHandler;
		procedure Set_IsMouseDirectlyOverChanged(Value : TDependencyPropertyChangedEventHandler);
		function Get_IsStylusCapturedChanged : TDependencyPropertyChangedEventHandler;
		procedure Set_IsStylusCapturedChanged(Value : TDependencyPropertyChangedEventHandler);
		function Get_IsStylusCaptureWithinChanged : TDependencyPropertyChangedEventHandler;
		procedure Set_IsStylusCaptureWithinChanged(Value : TDependencyPropertyChangedEventHandler);
		function Get_IsStylusDirectlyOverChanged : TDependencyPropertyChangedEventHandler;
		procedure Set_IsStylusDirectlyOverChanged(Value : TDependencyPropertyChangedEventHandler);
		function Get_IsVisibleChanged : TDependencyPropertyChangedEventHandler;
		procedure Set_IsVisibleChanged(Value : TDependencyPropertyChangedEventHandler);
		function Get_KeyDown : TKeyEventHandler;
		procedure Set_KeyDown(Value : TKeyEventHandler);
		function Get_KeyUp : TKeyEventHandler;
		procedure Set_KeyUp(Value : TKeyEventHandler);
		function Get_LayoutUpdated : TEventHandler_1;
		procedure Set_LayoutUpdated(Value : TEventHandler_1);
		function Get_Loaded : TRoutedEventHandler;
		procedure Set_Loaded(Value : TRoutedEventHandler);
		function Get_LostFocus : TRoutedEventHandler;
		procedure Set_LostFocus(Value : TRoutedEventHandler);
		function Get_LostKeyboardFocus : TKeyboardFocusChangedEventHandler;
		procedure Set_LostKeyboardFocus(Value : TKeyboardFocusChangedEventHandler);
		function Get_LostMouseCapture : TMouseEventHandler;
		procedure Set_LostMouseCapture(Value : TMouseEventHandler);
		function Get_LostStylusCapture : TStylusEventHandler;
		procedure Set_LostStylusCapture(Value : TStylusEventHandler);
		function Get_LostTouchCapture : TEventHandler;
		procedure Set_LostTouchCapture(Value : TEventHandler);
		function Get_ManipulationBoundaryFeedback : TEventHandler_2;
		procedure Set_ManipulationBoundaryFeedback(Value : TEventHandler_2);
		function Get_ManipulationCompleted : TEventHandler_3;
		procedure Set_ManipulationCompleted(Value : TEventHandler_3);
		function Get_ManipulationDelta : TEventHandler_4;
		procedure Set_ManipulationDelta(Value : TEventHandler_4);
		function Get_ManipulationInertiaStarting : TEventHandler_5;
		procedure Set_ManipulationInertiaStarting(Value : TEventHandler_5);
		function Get_ManipulationStarted : TEventHandler_6;
		procedure Set_ManipulationStarted(Value : TEventHandler_6);
		function Get_ManipulationStarting : TEventHandler_7;
		procedure Set_ManipulationStarting(Value : TEventHandler_7);
		function Get_MouseDown : TMouseButtonEventHandler;
		procedure Set_MouseDown(Value : TMouseButtonEventHandler);
		function Get_MouseEnter : TMouseEventHandler;
		procedure Set_MouseEnter(Value : TMouseEventHandler);
		function Get_MouseLeave : TMouseEventHandler;
		procedure Set_MouseLeave(Value : TMouseEventHandler);
		function Get_MouseLeftButtonDown : TMouseButtonEventHandler;
		procedure Set_MouseLeftButtonDown(Value : TMouseButtonEventHandler);
		function Get_MouseLeftButtonUp : TMouseButtonEventHandler;
		procedure Set_MouseLeftButtonUp(Value : TMouseButtonEventHandler);
		function Get_MouseMove : TMouseEventHandler;
		procedure Set_MouseMove(Value : TMouseEventHandler);
		function Get_MouseRightButtonDown : TMouseButtonEventHandler;
		procedure Set_MouseRightButtonDown(Value : TMouseButtonEventHandler);
		function Get_MouseRightButtonUp : TMouseButtonEventHandler;
		procedure Set_MouseRightButtonUp(Value : TMouseButtonEventHandler);
		function Get_MouseUp : TMouseButtonEventHandler;
		procedure Set_MouseUp(Value : TMouseButtonEventHandler);
		function Get_MouseWheel : TMouseWheelEventHandler;
		procedure Set_MouseWheel(Value : TMouseWheelEventHandler);
		function Get_OnButtonClick : TMyControlEventHandler;
		procedure Set_OnButtonClick(Value : TMyControlEventHandler);
		function Get_PreviewDragEnter : TDragEventHandler;
		procedure Set_PreviewDragEnter(Value : TDragEventHandler);
		function Get_PreviewDragLeave : TDragEventHandler;
		procedure Set_PreviewDragLeave(Value : TDragEventHandler);
		function Get_PreviewDragOver : TDragEventHandler;
		procedure Set_PreviewDragOver(Value : TDragEventHandler);
		function Get_PreviewDrop : TDragEventHandler;
		procedure Set_PreviewDrop(Value : TDragEventHandler);
		function Get_PreviewGiveFeedback : TGiveFeedbackEventHandler;
		procedure Set_PreviewGiveFeedback(Value : TGiveFeedbackEventHandler);
		function Get_PreviewGotKeyboardFocus : TKeyboardFocusChangedEventHandler;
		procedure Set_PreviewGotKeyboardFocus(Value : TKeyboardFocusChangedEventHandler);
		function Get_PreviewKeyDown : TKeyEventHandler;
		procedure Set_PreviewKeyDown(Value : TKeyEventHandler);
		function Get_PreviewKeyUp : TKeyEventHandler;
		procedure Set_PreviewKeyUp(Value : TKeyEventHandler);
		function Get_PreviewLostKeyboardFocus : TKeyboardFocusChangedEventHandler;
		procedure Set_PreviewLostKeyboardFocus(Value : TKeyboardFocusChangedEventHandler);
		function Get_PreviewMouseDown : TMouseButtonEventHandler;
		procedure Set_PreviewMouseDown(Value : TMouseButtonEventHandler);
		function Get_PreviewMouseLeftButtonDown : TMouseButtonEventHandler;
		procedure Set_PreviewMouseLeftButtonDown(Value : TMouseButtonEventHandler);
		function Get_PreviewMouseLeftButtonUp : TMouseButtonEventHandler;
		procedure Set_PreviewMouseLeftButtonUp(Value : TMouseButtonEventHandler);
		function Get_PreviewMouseMove : TMouseEventHandler;
		procedure Set_PreviewMouseMove(Value : TMouseEventHandler);
		function Get_PreviewMouseRightButtonDown : TMouseButtonEventHandler;
		procedure Set_PreviewMouseRightButtonDown(Value : TMouseButtonEventHandler);
		function Get_PreviewMouseRightButtonUp : TMouseButtonEventHandler;
		procedure Set_PreviewMouseRightButtonUp(Value : TMouseButtonEventHandler);
		function Get_PreviewMouseUp : TMouseButtonEventHandler;
		procedure Set_PreviewMouseUp(Value : TMouseButtonEventHandler);
		function Get_PreviewMouseWheel : TMouseWheelEventHandler;
		procedure Set_PreviewMouseWheel(Value : TMouseWheelEventHandler);
		function Get_PreviewQueryContinueDrag : TQueryContinueDragEventHandler;
		procedure Set_PreviewQueryContinueDrag(Value : TQueryContinueDragEventHandler);
		function Get_PreviewStylusButtonDown : TStylusButtonEventHandler;
		procedure Set_PreviewStylusButtonDown(Value : TStylusButtonEventHandler);
		function Get_PreviewStylusButtonUp : TStylusButtonEventHandler;
		procedure Set_PreviewStylusButtonUp(Value : TStylusButtonEventHandler);
		function Get_PreviewStylusDown : TStylusDownEventHandler;
		procedure Set_PreviewStylusDown(Value : TStylusDownEventHandler);
		function Get_PreviewStylusInAirMove : TStylusEventHandler;
		procedure Set_PreviewStylusInAirMove(Value : TStylusEventHandler);
		function Get_PreviewStylusInRange : TStylusEventHandler;
		procedure Set_PreviewStylusInRange(Value : TStylusEventHandler);
		function Get_PreviewStylusMove : TStylusEventHandler;
		procedure Set_PreviewStylusMove(Value : TStylusEventHandler);
		function Get_PreviewStylusOutOfRange : TStylusEventHandler;
		procedure Set_PreviewStylusOutOfRange(Value : TStylusEventHandler);
		function Get_PreviewStylusSystemGesture : TStylusSystemGestureEventHandler;
		procedure Set_PreviewStylusSystemGesture(Value : TStylusSystemGestureEventHandler);
		function Get_PreviewStylusUp : TStylusEventHandler;
		procedure Set_PreviewStylusUp(Value : TStylusEventHandler);
		function Get_PreviewTextInput : TTextCompositionEventHandler;
		procedure Set_PreviewTextInput(Value : TTextCompositionEventHandler);
		function Get_PreviewTouchDown : TEventHandler;
		procedure Set_PreviewTouchDown(Value : TEventHandler);
		function Get_PreviewTouchMove : TEventHandler;
		procedure Set_PreviewTouchMove(Value : TEventHandler);
		function Get_PreviewTouchUp : TEventHandler;
		procedure Set_PreviewTouchUp(Value : TEventHandler);
		function Get_QueryContinueDrag : TQueryContinueDragEventHandler;
		procedure Set_QueryContinueDrag(Value : TQueryContinueDragEventHandler);
		function Get_QueryCursor : TQueryCursorEventHandler;
		procedure Set_QueryCursor(Value : TQueryCursorEventHandler);
		function Get_RequestBringIntoView : TRequestBringIntoViewEventHandler;
		procedure Set_RequestBringIntoView(Value : TRequestBringIntoViewEventHandler);
		function Get_SizeChanged : TSizeChangedEventHandler;
		procedure Set_SizeChanged(Value : TSizeChangedEventHandler);
		function Get_SourceUpdated : TEventHandler_8;
		procedure Set_SourceUpdated(Value : TEventHandler_8);
		function Get_StylusButtonDown : TStylusButtonEventHandler;
		procedure Set_StylusButtonDown(Value : TStylusButtonEventHandler);
		function Get_StylusButtonUp : TStylusButtonEventHandler;
		procedure Set_StylusButtonUp(Value : TStylusButtonEventHandler);
		function Get_StylusDown : TStylusDownEventHandler;
		procedure Set_StylusDown(Value : TStylusDownEventHandler);
		function Get_StylusEnter : TStylusEventHandler;
		procedure Set_StylusEnter(Value : TStylusEventHandler);
		function Get_StylusInAirMove : TStylusEventHandler;
		procedure Set_StylusInAirMove(Value : TStylusEventHandler);
		function Get_StylusInRange : TStylusEventHandler;
		procedure Set_StylusInRange(Value : TStylusEventHandler);
		function Get_StylusLeave : TStylusEventHandler;
		procedure Set_StylusLeave(Value : TStylusEventHandler);
		function Get_StylusMove : TStylusEventHandler;
		procedure Set_StylusMove(Value : TStylusEventHandler);
		function Get_StylusOutOfRange : TStylusEventHandler;
		procedure Set_StylusOutOfRange(Value : TStylusEventHandler);
		function Get_StylusSystemGesture : TStylusSystemGestureEventHandler;
		procedure Set_StylusSystemGesture(Value : TStylusSystemGestureEventHandler);
		function Get_StylusUp : TStylusEventHandler;
		procedure Set_StylusUp(Value : TStylusEventHandler);
		function Get_TargetUpdated : TEventHandler_8;
		procedure Set_TargetUpdated(Value : TEventHandler_8);
		function Get_TextInput : TTextCompositionEventHandler;
		procedure Set_TextInput(Value : TTextCompositionEventHandler);
		function Get_ToolTipClosing : TToolTipEventHandler;
		procedure Set_ToolTipClosing(Value : TToolTipEventHandler);
		function Get_ToolTipOpening : TToolTipEventHandler;
		procedure Set_ToolTipOpening(Value : TToolTipEventHandler);
		function Get_TouchDown : TEventHandler;
		procedure Set_TouchDown(Value : TEventHandler);
		function Get_TouchEnter : TEventHandler;
		procedure Set_TouchEnter(Value : TEventHandler);
		function Get_TouchLeave : TEventHandler;
		procedure Set_TouchLeave(Value : TEventHandler);
		function Get_TouchMove : TEventHandler;
		procedure Set_TouchMove(Value : TEventHandler);
		function Get_TouchUp : TEventHandler;
		procedure Set_TouchUp(Value : TEventHandler);
		function Get_Unloaded : TRoutedEventHandler;
		procedure Set_Unloaded(Value : TRoutedEventHandler);
		{ public }
		procedure AddHandler(routedEvent: _RoutedEvent; handler: _Delegate); overload;
		procedure AddHandler(routedEvent: _RoutedEvent; handler: _Delegate; handledEventsToo: Boolean); overload;
		procedure AddToEventRoute(route: _EventRoute; e: _RoutedEventArgs);
		procedure ApplyAnimationClock(dp: _DependencyProperty; clock: _AnimationClock); overload;
		procedure ApplyAnimationClock(dp: _DependencyProperty; clock: _AnimationClock; handoffBehavior: THandoffBehavior); overload;
		function ApplyTemplate: Boolean;
		procedure Arrange(finalRect: _Rect);
		procedure BeginAnimation(dp: _DependencyProperty; animation: _AnimationTimeline); overload;
		procedure BeginAnimation(dp: _DependencyProperty; animation: _AnimationTimeline; handoffBehavior: THandoffBehavior); overload;
		procedure BeginInit;
		procedure BeginStoryboard(storyboard: _Storyboard); overload;
		procedure BeginStoryboard(storyboard: _Storyboard; handoffBehavior: THandoffBehavior); overload;
		procedure BeginStoryboard(storyboard: _Storyboard; handoffBehavior: THandoffBehavior; isControllable: Boolean); overload;
		procedure BringIntoView; overload;
		procedure BringIntoView(targetRectangle: _Rect); overload;
		function CaptureMouse: Boolean;
		function CaptureStylus: Boolean;
		function CaptureTouch(touchDevice: _TouchDevice): Boolean;
		function CheckAccess: Boolean;
		procedure ClearValue(dp: _DependencyProperty); overload;
		procedure ClearValue(key: _DependencyPropertyKey); overload;
		procedure CoerceValue(dp: _DependencyProperty);
		procedure EndInit;
		function FindCommonVisualAncestor(otherVisual: _DependencyObject): _DependencyObject;
		function FindName(name: String): Olevariant;
		function FindResource(resourceKey: Olevariant): Olevariant;
		function Focus: Boolean;
		function GetAnimationBaseValue(dp: _DependencyProperty): Olevariant;
		function GetBindingExpression(dp: _DependencyProperty): _BindingExpression;
		function GetLocalValueEnumerator: _LocalValueEnumerator;
		function GetValue(dp: _DependencyProperty): Olevariant;
		procedure InitializeComponent;
		function InputHitTest(point: _Point): _IInputElement;
		procedure InvalidateArrange;
		procedure InvalidateMeasure;
		procedure InvalidateProperty(dp: _DependencyProperty);
		procedure InvalidateVisual;
		function IsAncestorOf(descendant: _DependencyObject): Boolean;
		function IsDescendantOf(ancestor: _DependencyObject): Boolean;
		procedure Measure(availableSize: _Size);
		function MoveFocus(request: _TraversalRequest): Boolean;
		procedure OnApplyTemplate;
		function PointFromScreen(point: _Point): _Point;
		function PointToScreen(point: _Point): _Point;
		function PredictFocus(direction: TFocusNavigationDirection): _DependencyObject;
		procedure RaiseEvent(e: _RoutedEventArgs);
		function ReadLocalValue(dp: _DependencyProperty): Olevariant;
		procedure RegisterName(name: String; scopedElement: Olevariant);
		procedure ReleaseAllTouchCaptures;
		procedure ReleaseMouseCapture;
		procedure ReleaseStylusCapture;
		function ReleaseTouchCapture(touchDevice: _TouchDevice): Boolean;
		procedure RemoveHandler(routedEvent: _RoutedEvent; handler: _Delegate);
		function SetBinding(dp: _DependencyProperty; binding: _BindingBase): _BindingExpressionBase; overload;
		function SetBinding(dp: _DependencyProperty; path: String): _BindingExpression; overload;
		procedure SetCurrentValue(dp: _DependencyProperty; value: Olevariant);
		procedure SetResourceReference(dp: _DependencyProperty; name: Olevariant);
		procedure SetValue(dp: _DependencyProperty; value: Olevariant); overload;
		procedure SetValue(key: _DependencyPropertyKey; value: Olevariant); overload;
		function ShouldSerializeChildren: Boolean;
		function ShouldSerializeColumnDefinitions: Boolean;
		function ShouldSerializeCommandBindings: Boolean;
		function ShouldSerializeInputBindings: Boolean;
		function ShouldSerializeResources: Boolean;
		function ShouldSerializeRowDefinitions: Boolean;
		function ShouldSerializeStyle: Boolean;
		function ShouldSerializeTriggers: Boolean;
		function TransformToAncestor(ancestor: _Visual): _GeneralTransform; overload;
		function TransformToAncestor(ancestor: _Visual3D): _GeneralTransform2DTo3D; overload;
		function TransformToDescendant(descendant: _Visual): _GeneralTransform;
		function TransformToVisual(visual: _Visual): _GeneralTransform;
		function TranslatePoint(point: _Point; relativeTo: _UIElement): _Point;
		function TryFindResource(resourceKey: Olevariant): Olevariant;
		procedure UnregisterName(name: String);
		procedure UpdateDefaultStyle;
		procedure UpdateLayout;
		procedure VerifyAccess;
		property ActualHeight: Double read Get_ActualHeight;
		property ActualWidth: Double read Get_ActualWidth;
		property AllowDrop: Boolean read Get_AllowDrop write Set_AllowDrop;
		property AreAnyTouchesCaptured: Boolean read Get_AreAnyTouchesCaptured;
		property AreAnyTouchesCapturedWithin: Boolean read Get_AreAnyTouchesCapturedWithin;
		property AreAnyTouchesDirectlyOver: Boolean read Get_AreAnyTouchesDirectlyOver;
		property AreAnyTouchesOver: Boolean read Get_AreAnyTouchesOver;
		property Background: _Brush read Get_Background write Set_Background;
		property BindingGroup: _BindingGroup read Get_BindingGroup write Set_BindingGroup;
		property BitmapEffect: IBitmapEffect read Get_BitmapEffect write Set_BitmapEffect;
		property BitmapEffectInput: IBitmapEffectInput read Get_BitmapEffectInput write Set_BitmapEffectInput;
		property CacheMode: _CacheMode read Get_CacheMode write Set_CacheMode;
		property Children: _UIElementCollection read Get_Children;
		property Clip: _Geometry read Get_Clip write Set_Clip;
		property ClipToBounds: Boolean read Get_ClipToBounds write Set_ClipToBounds;
		property ColumnDefinitions: IColumnDefinitionCollection read Get_ColumnDefinitions;
		property CommandBindings: _CommandBindingCollection read Get_CommandBindings;
		property ContextMenu: IContextMenu read Get_ContextMenu write Set_ContextMenu;
		property Cursor: ICursor read Get_Cursor write Set_Cursor;
		property DataContext: Olevariant read Get_DataContext write Set_DataContext;
		property DependencyObjectType: _DependencyObjectType read Get_DependencyObjectType;
		property DesiredSize: _Size read Get_DesiredSize;
		property Dispatcher: _Dispatcher read Get_Dispatcher;
		property Effect: _Effect read Get_Effect write Set_Effect;
		property FlowDirection: TFlowDirection read Get_FlowDirection write Set_FlowDirection;
		property Focusable: Boolean read Get_Focusable write Set_Focusable;
		property FocusVisualStyle: IStyle read Get_FocusVisualStyle write Set_FocusVisualStyle;
		property ForceCursor: Boolean read Get_ForceCursor write Set_ForceCursor;
		property HasAnimatedProperties: Boolean read Get_HasAnimatedProperties;
		property HasLogicalOrientationPublic: Boolean read Get_HasLogicalOrientationPublic;
		property Height: Double read Get_Height write Set_Height;
		property HorizontalAlignment: THorizontalAlignment read Get_HorizontalAlignment write Set_HorizontalAlignment;
		property InputBindings: _InputBindingCollection read Get_InputBindings;
		property InputScope: _InputScope read Get_InputScope write Set_InputScope;
		property IsArrangeValid: Boolean read Get_IsArrangeValid;
		property IsEnabled: Boolean read Get_IsEnabled write Set_IsEnabled;
		property IsFocused: Boolean read Get_IsFocused;
		property IsHitTestVisible: Boolean read Get_IsHitTestVisible write Set_IsHitTestVisible;
		property IsInitialized: Boolean read Get_IsInitialized;
		property IsInputMethodEnabled: Boolean read Get_IsInputMethodEnabled;
		property IsItemsHost: Boolean read Get_IsItemsHost write Set_IsItemsHost;
		property IsKeyboardFocused: Boolean read Get_IsKeyboardFocused;
		property IsKeyboardFocusWithin: Boolean read Get_IsKeyboardFocusWithin;
		property IsLoaded: Boolean read Get_IsLoaded;
		property IsManipulationEnabled: Boolean read Get_IsManipulationEnabled write Set_IsManipulationEnabled;
		property IsMeasureValid: Boolean read Get_IsMeasureValid;
		property IsMouseCaptured: Boolean read Get_IsMouseCaptured;
		property IsMouseCaptureWithin: Boolean read Get_IsMouseCaptureWithin;
		property IsMouseDirectlyOver: Boolean read Get_IsMouseDirectlyOver;
		property IsMouseOver: Boolean read Get_IsMouseOver;
		property IsSealed: Boolean read Get_IsSealed;
		property IsStylusCaptured: Boolean read Get_IsStylusCaptured;
		property IsStylusCaptureWithin: Boolean read Get_IsStylusCaptureWithin;
		property IsStylusDirectlyOver: Boolean read Get_IsStylusDirectlyOver;
		property IsStylusOver: Boolean read Get_IsStylusOver;
		property IsVisible: Boolean read Get_IsVisible;
		property Language: _XmlLanguage read Get_Language write Set_Language;
		property LayoutTransform: _Transform read Get_LayoutTransform write Set_LayoutTransform;
		property LogicalOrientationPublic: TOrientation read Get_LogicalOrientationPublic;
		property Margin: _Thickness read Get_Margin write Set_Margin;
		property MaxHeight: Double read Get_MaxHeight write Set_MaxHeight;
		property MaxWidth: Double read Get_MaxWidth write Set_MaxWidth;
		property MinHeight: Double read Get_MinHeight write Set_MinHeight;
		property MinWidth: Double read Get_MinWidth write Set_MinWidth;
		property MyControl_Background: ISolidColorBrush read Get_MyControl_Background write Set_MyControl_Background;
		property MyControl_FontFamily: _FontFamily read Get_MyControl_FontFamily write Set_MyControl_FontFamily;
		property MyControl_FontSize: Double read Get_MyControl_FontSize write Set_MyControl_FontSize;
		property MyControl_FontStyle: _FontStyle read Get_MyControl_FontStyle write Set_MyControl_FontStyle;
		property MyControl_FontWeight: _FontWeight read Get_MyControl_FontWeight write Set_MyControl_FontWeight;
		property MyControl_Foreground: ISolidColorBrush read Get_MyControl_Foreground write Set_MyControl_Foreground;
		property Name: String read Get_Name write Set_Name;
		property Opacity: Double read Get_Opacity write Set_Opacity;
		property OpacityMask: _Brush read Get_OpacityMask write Set_OpacityMask;
		property OverridesDefaultStyle: Boolean read Get_OverridesDefaultStyle write Set_OverridesDefaultStyle;
		property Parent: _DependencyObject read Get_Parent;
		property PersistId: Integer read Get_PersistId;
		property RenderSize: _Size read Get_RenderSize write Set_RenderSize;
		property RenderTransform: _Transform read Get_RenderTransform write Set_RenderTransform;
		property RenderTransformOrigin: _Point read Get_RenderTransformOrigin write Set_RenderTransformOrigin;
		property Resources: _ResourceDictionary read Get_Resources write Set_Resources;
		property RowDefinitions: IRowDefinitionCollection read Get_RowDefinitions;
		property ShowGridLines: Boolean read Get_ShowGridLines write Set_ShowGridLines;
		property SnapsToDevicePixels: Boolean read Get_SnapsToDevicePixels write Set_SnapsToDevicePixels;
		property Style: IStyle read Get_Style write Set_Style;
		property Tag: Olevariant read Get_Tag write Set_Tag;
		property TemplatedParent: _DependencyObject read Get_TemplatedParent;
		property ToolTip: Olevariant read Get_ToolTip write Set_ToolTip;
		property TouchesCaptured: IList<_TouchDevice> read Get_TouchesCaptured;
		property TouchesCapturedWithin: IList<_TouchDevice> read Get_TouchesCapturedWithin;
		property TouchesDirectlyOver: IList<_TouchDevice> read Get_TouchesDirectlyOver;
		property TouchesOver: IList<_TouchDevice> read Get_TouchesOver;
		property Triggers: _TriggerCollection read Get_Triggers;
		property Uid: String read Get_Uid write Set_Uid;
		property UseLayoutRounding: Boolean read Get_UseLayoutRounding write Set_UseLayoutRounding;
		property VerticalAlignment: TVerticalAlignment read Get_VerticalAlignment write Set_VerticalAlignment;
		property Visibility: TVisibility read Get_Visibility write Set_Visibility;
		property Width: Double read Get_Width write Set_Width;
		property ContextMenuClosing: TContextMenuEventHandler read Get_ContextMenuClosing write Set_ContextMenuClosing;
		property ContextMenuOpening: TContextMenuEventHandler read Get_ContextMenuOpening write Set_ContextMenuOpening;
		property DataContextChanged: TDependencyPropertyChangedEventHandler read Get_DataContextChanged write Set_DataContextChanged;
		property DragEnter: TDragEventHandler read Get_DragEnter write Set_DragEnter;
		property DragLeave: TDragEventHandler read Get_DragLeave write Set_DragLeave;
		property DragOver: TDragEventHandler read Get_DragOver write Set_DragOver;
		property Drop: TDragEventHandler read Get_Drop write Set_Drop;
		property FocusableChanged: TDependencyPropertyChangedEventHandler read Get_FocusableChanged write Set_FocusableChanged;
		property GiveFeedback: TGiveFeedbackEventHandler read Get_GiveFeedback write Set_GiveFeedback;
		property GotFocus: TRoutedEventHandler read Get_GotFocus write Set_GotFocus;
		property GotKeyboardFocus: TKeyboardFocusChangedEventHandler read Get_GotKeyboardFocus write Set_GotKeyboardFocus;
		property GotMouseCapture: TMouseEventHandler read Get_GotMouseCapture write Set_GotMouseCapture;
		property GotStylusCapture: TStylusEventHandler read Get_GotStylusCapture write Set_GotStylusCapture;
		property GotTouchCapture: TEventHandler read Get_GotTouchCapture write Set_GotTouchCapture;
		property Initialized: TEventHandler_1 read Get_Initialized write Set_Initialized;
		property IsEnabledChanged: TDependencyPropertyChangedEventHandler read Get_IsEnabledChanged write Set_IsEnabledChanged;
		property IsHitTestVisibleChanged: TDependencyPropertyChangedEventHandler read Get_IsHitTestVisibleChanged write Set_IsHitTestVisibleChanged;
		property IsKeyboardFocusedChanged: TDependencyPropertyChangedEventHandler read Get_IsKeyboardFocusedChanged write Set_IsKeyboardFocusedChanged;
		property IsKeyboardFocusWithinChanged: TDependencyPropertyChangedEventHandler read Get_IsKeyboardFocusWithinChanged write Set_IsKeyboardFocusWithinChanged;
		property IsMouseCapturedChanged: TDependencyPropertyChangedEventHandler read Get_IsMouseCapturedChanged write Set_IsMouseCapturedChanged;
		property IsMouseCaptureWithinChanged: TDependencyPropertyChangedEventHandler read Get_IsMouseCaptureWithinChanged write Set_IsMouseCaptureWithinChanged;
		property IsMouseDirectlyOverChanged: TDependencyPropertyChangedEventHandler read Get_IsMouseDirectlyOverChanged write Set_IsMouseDirectlyOverChanged;
		property IsStylusCapturedChanged: TDependencyPropertyChangedEventHandler read Get_IsStylusCapturedChanged write Set_IsStylusCapturedChanged;
		property IsStylusCaptureWithinChanged: TDependencyPropertyChangedEventHandler read Get_IsStylusCaptureWithinChanged write Set_IsStylusCaptureWithinChanged;
		property IsStylusDirectlyOverChanged: TDependencyPropertyChangedEventHandler read Get_IsStylusDirectlyOverChanged write Set_IsStylusDirectlyOverChanged;
		property IsVisibleChanged: TDependencyPropertyChangedEventHandler read Get_IsVisibleChanged write Set_IsVisibleChanged;
		property KeyDown: TKeyEventHandler read Get_KeyDown write Set_KeyDown;
		property KeyUp: TKeyEventHandler read Get_KeyUp write Set_KeyUp;
		property LayoutUpdated: TEventHandler_1 read Get_LayoutUpdated write Set_LayoutUpdated;
		property Loaded: TRoutedEventHandler read Get_Loaded write Set_Loaded;
		property LostFocus: TRoutedEventHandler read Get_LostFocus write Set_LostFocus;
		property LostKeyboardFocus: TKeyboardFocusChangedEventHandler read Get_LostKeyboardFocus write Set_LostKeyboardFocus;
		property LostMouseCapture: TMouseEventHandler read Get_LostMouseCapture write Set_LostMouseCapture;
		property LostStylusCapture: TStylusEventHandler read Get_LostStylusCapture write Set_LostStylusCapture;
		property LostTouchCapture: TEventHandler read Get_LostTouchCapture write Set_LostTouchCapture;
		property ManipulationBoundaryFeedback: TEventHandler_2 read Get_ManipulationBoundaryFeedback write Set_ManipulationBoundaryFeedback;
		property ManipulationCompleted: TEventHandler_3 read Get_ManipulationCompleted write Set_ManipulationCompleted;
		property ManipulationDelta: TEventHandler_4 read Get_ManipulationDelta write Set_ManipulationDelta;
		property ManipulationInertiaStarting: TEventHandler_5 read Get_ManipulationInertiaStarting write Set_ManipulationInertiaStarting;
		property ManipulationStarted: TEventHandler_6 read Get_ManipulationStarted write Set_ManipulationStarted;
		property ManipulationStarting: TEventHandler_7 read Get_ManipulationStarting write Set_ManipulationStarting;
		property MouseDown: TMouseButtonEventHandler read Get_MouseDown write Set_MouseDown;
		property MouseEnter: TMouseEventHandler read Get_MouseEnter write Set_MouseEnter;
		property MouseLeave: TMouseEventHandler read Get_MouseLeave write Set_MouseLeave;
		property MouseLeftButtonDown: TMouseButtonEventHandler read Get_MouseLeftButtonDown write Set_MouseLeftButtonDown;
		property MouseLeftButtonUp: TMouseButtonEventHandler read Get_MouseLeftButtonUp write Set_MouseLeftButtonUp;
		property MouseMove: TMouseEventHandler read Get_MouseMove write Set_MouseMove;
		property MouseRightButtonDown: TMouseButtonEventHandler read Get_MouseRightButtonDown write Set_MouseRightButtonDown;
		property MouseRightButtonUp: TMouseButtonEventHandler read Get_MouseRightButtonUp write Set_MouseRightButtonUp;
		property MouseUp: TMouseButtonEventHandler read Get_MouseUp write Set_MouseUp;
		property MouseWheel: TMouseWheelEventHandler read Get_MouseWheel write Set_MouseWheel;
		property OnButtonClick: TMyControlEventHandler read Get_OnButtonClick write Set_OnButtonClick;
		property PreviewDragEnter: TDragEventHandler read Get_PreviewDragEnter write Set_PreviewDragEnter;
		property PreviewDragLeave: TDragEventHandler read Get_PreviewDragLeave write Set_PreviewDragLeave;
		property PreviewDragOver: TDragEventHandler read Get_PreviewDragOver write Set_PreviewDragOver;
		property PreviewDrop: TDragEventHandler read Get_PreviewDrop write Set_PreviewDrop;
		property PreviewGiveFeedback: TGiveFeedbackEventHandler read Get_PreviewGiveFeedback write Set_PreviewGiveFeedback;
		property PreviewGotKeyboardFocus: TKeyboardFocusChangedEventHandler read Get_PreviewGotKeyboardFocus write Set_PreviewGotKeyboardFocus;
		property PreviewKeyDown: TKeyEventHandler read Get_PreviewKeyDown write Set_PreviewKeyDown;
		property PreviewKeyUp: TKeyEventHandler read Get_PreviewKeyUp write Set_PreviewKeyUp;
		property PreviewLostKeyboardFocus: TKeyboardFocusChangedEventHandler read Get_PreviewLostKeyboardFocus write Set_PreviewLostKeyboardFocus;
		property PreviewMouseDown: TMouseButtonEventHandler read Get_PreviewMouseDown write Set_PreviewMouseDown;
		property PreviewMouseLeftButtonDown: TMouseButtonEventHandler read Get_PreviewMouseLeftButtonDown write Set_PreviewMouseLeftButtonDown;
		property PreviewMouseLeftButtonUp: TMouseButtonEventHandler read Get_PreviewMouseLeftButtonUp write Set_PreviewMouseLeftButtonUp;
		property PreviewMouseMove: TMouseEventHandler read Get_PreviewMouseMove write Set_PreviewMouseMove;
		property PreviewMouseRightButtonDown: TMouseButtonEventHandler read Get_PreviewMouseRightButtonDown write Set_PreviewMouseRightButtonDown;
		property PreviewMouseRightButtonUp: TMouseButtonEventHandler read Get_PreviewMouseRightButtonUp write Set_PreviewMouseRightButtonUp;
		property PreviewMouseUp: TMouseButtonEventHandler read Get_PreviewMouseUp write Set_PreviewMouseUp;
		property PreviewMouseWheel: TMouseWheelEventHandler read Get_PreviewMouseWheel write Set_PreviewMouseWheel;
		property PreviewQueryContinueDrag: TQueryContinueDragEventHandler read Get_PreviewQueryContinueDrag write Set_PreviewQueryContinueDrag;
		property PreviewStylusButtonDown: TStylusButtonEventHandler read Get_PreviewStylusButtonDown write Set_PreviewStylusButtonDown;
		property PreviewStylusButtonUp: TStylusButtonEventHandler read Get_PreviewStylusButtonUp write Set_PreviewStylusButtonUp;
		property PreviewStylusDown: TStylusDownEventHandler read Get_PreviewStylusDown write Set_PreviewStylusDown;
		property PreviewStylusInAirMove: TStylusEventHandler read Get_PreviewStylusInAirMove write Set_PreviewStylusInAirMove;
		property PreviewStylusInRange: TStylusEventHandler read Get_PreviewStylusInRange write Set_PreviewStylusInRange;
		property PreviewStylusMove: TStylusEventHandler read Get_PreviewStylusMove write Set_PreviewStylusMove;
		property PreviewStylusOutOfRange: TStylusEventHandler read Get_PreviewStylusOutOfRange write Set_PreviewStylusOutOfRange;
		property PreviewStylusSystemGesture: TStylusSystemGestureEventHandler read Get_PreviewStylusSystemGesture write Set_PreviewStylusSystemGesture;
		property PreviewStylusUp: TStylusEventHandler read Get_PreviewStylusUp write Set_PreviewStylusUp;
		property PreviewTextInput: TTextCompositionEventHandler read Get_PreviewTextInput write Set_PreviewTextInput;
		property PreviewTouchDown: TEventHandler read Get_PreviewTouchDown write Set_PreviewTouchDown;
		property PreviewTouchMove: TEventHandler read Get_PreviewTouchMove write Set_PreviewTouchMove;
		property PreviewTouchUp: TEventHandler read Get_PreviewTouchUp write Set_PreviewTouchUp;
		property QueryContinueDrag: TQueryContinueDragEventHandler read Get_QueryContinueDrag write Set_QueryContinueDrag;
		property QueryCursor: TQueryCursorEventHandler read Get_QueryCursor write Set_QueryCursor;
		property RequestBringIntoView: TRequestBringIntoViewEventHandler read Get_RequestBringIntoView write Set_RequestBringIntoView;
		property SizeChanged: TSizeChangedEventHandler read Get_SizeChanged write Set_SizeChanged;
		property SourceUpdated: TEventHandler_8 read Get_SourceUpdated write Set_SourceUpdated;
		property StylusButtonDown: TStylusButtonEventHandler read Get_StylusButtonDown write Set_StylusButtonDown;
		property StylusButtonUp: TStylusButtonEventHandler read Get_StylusButtonUp write Set_StylusButtonUp;
		property StylusDown: TStylusDownEventHandler read Get_StylusDown write Set_StylusDown;
		property StylusEnter: TStylusEventHandler read Get_StylusEnter write Set_StylusEnter;
		property StylusInAirMove: TStylusEventHandler read Get_StylusInAirMove write Set_StylusInAirMove;
		property StylusInRange: TStylusEventHandler read Get_StylusInRange write Set_StylusInRange;
		property StylusLeave: TStylusEventHandler read Get_StylusLeave write Set_StylusLeave;
		property StylusMove: TStylusEventHandler read Get_StylusMove write Set_StylusMove;
		property StylusOutOfRange: TStylusEventHandler read Get_StylusOutOfRange write Set_StylusOutOfRange;
		property StylusSystemGesture: TStylusSystemGestureEventHandler read Get_StylusSystemGesture write Set_StylusSystemGesture;
		property StylusUp: TStylusEventHandler read Get_StylusUp write Set_StylusUp;
		property TargetUpdated: TEventHandler_8 read Get_TargetUpdated write Set_TargetUpdated;
		property TextInput: TTextCompositionEventHandler read Get_TextInput write Set_TextInput;
		property ToolTipClosing: TToolTipEventHandler read Get_ToolTipClosing write Set_ToolTipClosing;
		property ToolTipOpening: TToolTipEventHandler read Get_ToolTipOpening write Set_ToolTipOpening;
		property TouchDown: TEventHandler read Get_TouchDown write Set_TouchDown;
		property TouchEnter: TEventHandler read Get_TouchEnter write Set_TouchEnter;
		property TouchLeave: TEventHandler read Get_TouchLeave write Set_TouchLeave;
		property TouchMove: TEventHandler read Get_TouchMove write Set_TouchMove;
		property TouchUp: TEventHandler read Get_TouchUp write Set_TouchUp;
		property Unloaded: TRoutedEventHandler read Get_Unloaded write Set_Unloaded;
	end;

	[TypeMapping(sD_TMyControlEventArgs, sC_MyC_MyControlEventArgs)]
	IMyControlEventArgs = interface
		{ private }
		function Get_IsOK: Boolean;
		procedure Set_IsOK(Value: Boolean);
		function Get_MyCity: String;
		procedure Set_MyCity(Value: String);
		function Get_MyName: String;
		procedure Set_MyName(Value: String);
		function Get_MyState: String;
		procedure Set_MyState(Value: String);
		function Get_MyStreetAddress: String;
		procedure Set_MyStreetAddress(Value: String);
		function Get_MyZip: String;
		procedure Set_MyZip(Value: String);
		{ public }
		property IsOK: Boolean read Get_IsOK write Set_IsOK;
		property MyCity: String read Get_MyCity write Set_MyCity;
		property MyName: String read Get_MyName write Set_MyName;
		property MyState: String read Get_MyState write Set_MyState;
		property MyStreetAddress: String read Get_MyStreetAddress write Set_MyStreetAddress;
		property MyZip: String read Get_MyZip write Set_MyZip;
	end;

implementation

end.

