(*
 * Generated by .Net DLL/WSDL Import Utility for Delphi
 *
 * Version:  6.0.5.1
 *
 * File generated on 09/11/2018 21:55:38 from .Net Library location below.
 *    .Net Library Path: C:/Users/Bismark/Downloads/HostWPFInVCLFormsDelphi/WPFInVCL/WPF_MyControls_CSharp/MyControls/MyControls/bin/Release/MyControls.dll
 *
 * Home: https://www.crystalnet-tech.com/RuntimeLibrary/RuntimeLibrary4Delphi
 *)

unit MyControls.Enums;

{$WARN BOUNDS_ERROR OFF}

interface

uses
	{$IF CompilerVersion > 22}
	Winapi.ActiveX 
{$ELSE}
	ActiveX 
{$IFEND};

type
	FlowDirection = TOleEnum;
const
	FlowDirection_LeftToRight = $00000000;
	FlowDirection_RightToLeft = $00000001;

type
	HorizontalAlignment = TOleEnum;
const
	HorizontalAlignment_Left = $00000000;
	HorizontalAlignment_Center = $00000001;
	HorizontalAlignment_Right = $00000002;
	HorizontalAlignment_Stretch = $00000003;

type
	Orientation = TOleEnum;
const
	Orientation_Horizontal = $00000000;
	Orientation_Vertical = $00000001;

type
	VerticalAlignment = TOleEnum;
const
	VerticalAlignment_Top = $00000000;
	VerticalAlignment_Center = $00000001;
	VerticalAlignment_Bottom = $00000002;
	VerticalAlignment_Stretch = $00000003;

type
	Visibility = TOleEnum;
const
	Visibility_Visible = $00;
	Visibility_Hidden = $01;
	Visibility_Collapsed = $02;

type
	HandoffBehavior = TOleEnum;
const
	HandoffBehavior_SnapshotAndReplace = $00000000;
	HandoffBehavior_Compose = $00000001;

type
	FocusNavigationDirection = TOleEnum;
const
	FocusNavigationDirection_Next = $00000000;
	FocusNavigationDirection_Previous = $00000001;
	FocusNavigationDirection_First = $00000002;
	FocusNavigationDirection_Last = $00000003;
	FocusNavigationDirection_Left = $00000004;
	FocusNavigationDirection_Right = $00000005;
	FocusNavigationDirection_Up = $00000006;
	FocusNavigationDirection_Down = $00000007;

type
	TFlowDirection = 
	(
		fdLeftToRight, 
		fdRightToLeft
	);

	THorizontalAlignment = 
	(
		haLeft, 
		haCenter, 
		haRight, 
		haStretch
	);

	TOrientation = 
	(
		orientationHorizontal, 
		orientationVertical
	);

	TVerticalAlignment = 
	(
		vaTop, 
		vaCenter, 
		vaBottom, 
		vaStretch
	);

	TVisibility = 
	(
		visibilityVisible, 
		visibilityHidden, 
		visibilityCollapsed
	);

	THandoffBehavior = 
	(
		hbSnapshotAndReplace, 
		hbCompose
	);

	TFocusNavigationDirection = 
	(
		fndNext, 
		fndPrevious, 
		fndFirst, 
		fndLast, 
		fndLeft, 
		fndRight, 
		fndUp, 
		fndDown
	);

const

	FlowDirectionValues: array[TFlowDirection] of TOleEnum =
	(
		FlowDirection_LeftToRight, 
		FlowDirection_RightToLeft
	);

	HorizontalAlignmentValues: array[THorizontalAlignment] of TOleEnum =
	(
		HorizontalAlignment_Left, 
		HorizontalAlignment_Center, 
		HorizontalAlignment_Right, 
		HorizontalAlignment_Stretch
	);

	OrientationValues: array[TOrientation] of TOleEnum =
	(
		Orientation_Horizontal, 
		Orientation_Vertical
	);

	VerticalAlignmentValues: array[TVerticalAlignment] of TOleEnum =
	(
		VerticalAlignment_Top, 
		VerticalAlignment_Center, 
		VerticalAlignment_Bottom, 
		VerticalAlignment_Stretch
	);

	VisibilityValues: array[TVisibility] of TOleEnum =
	(
		Visibility_Visible, 
		Visibility_Hidden, 
		Visibility_Collapsed
	);

	HandoffBehaviorValues: array[THandoffBehavior] of TOleEnum =
	(
		HandoffBehavior_SnapshotAndReplace, 
		HandoffBehavior_Compose
	);

	FocusNavigationDirectionValues: array[TFocusNavigationDirection] of TOleEnum =
	(
		FocusNavigationDirection_Next, 
		FocusNavigationDirection_Previous, 
		FocusNavigationDirection_First, 
		FocusNavigationDirection_Last, 
		FocusNavigationDirection_Left, 
		FocusNavigationDirection_Right, 
		FocusNavigationDirection_Up, 
		FocusNavigationDirection_Down
	);



implementation

end.

