(*
 * Generated by .Net DLL/WSDL Import Utility for Delphi
 *
 * Version:  6.0.5.1
 *
 * File generated on 09/11/2018 21:55:38 from .Net Library location below.
 *    .Net Library Path: C:/Users/Bismark/Downloads/HostWPFInVCLFormsDelphi/WPFInVCL/WPF_MyControls_CSharp/MyControls/MyControls/bin/Release/MyControls.dll
 *
 * Home: https://www.crystalnet-tech.com/RuntimeLibrary/RuntimeLibrary4Delphi
 *)

unit MyControls.Consts;

interface

const

	sC_MyControls_Asm_ID = '3958640c-9f48-48a3-8237-4e6a60b3e51b';
	sC_MyControls_sC_AssemblyPath = 'MyControls.dll';

	sC_MyC_MyControl1 = 'MyControls.MyControl1';
	sC_MyC_MyControlEventArgs = 'MyControls.MyControlEventArgs';
	sC_MyControls_sC_WSDLDomain = 'sC_MyControls_sC_WSDLDomain';
	sC_MyControls_sC_WSDLPassword = 'C:/Users/Bismark/Downloads/HostWPFInVCLFormsDelphi/WPFInVCL/WPF_MyControls_CSharp/MyControls/MyControls/bin/Release/MyControls.dll';
	sC_MyControls_sC_WSDLUserName = 'C:/Users/Bismark/Downloads/HostWPFInVCLFormsDelphi/WPFInVCL/WPF_MyControls_CSharp/MyControls/MyControls/bin/Release/MyControls.dll';
	sC_Sys_Boolean = 'System.Boolean';
	sC_Sys_Delegate = 'System.Delegate';
	sC_Sys_EventArgs = 'System.EventArgs';
	sC_Sys_Object_ = 'System.Object';
	sC_Sys_String_ = 'System.String';
	sC_Sys_Void = 'System.Void';
	sC_SysWin_DependencyObject = 'System.Windows.DependencyObject';
	sC_SysWin_DependencyProperty = 'System.Windows.DependencyProperty';
	sC_SysWin_DependencyPropertyChangedEventArgs = 'System.Windows.DependencyPropertyChangedEventArgs';
	sC_SysWin_DependencyPropertyKey = 'System.Windows.DependencyPropertyKey';
	sC_SysWin_DragEventArgs = 'System.Windows.DragEventArgs';
	sC_SysWin_EventRoute = 'System.Windows.EventRoute';
	sC_SysWin_GiveFeedbackEventArgs = 'System.Windows.GiveFeedbackEventArgs';
	sC_SysWin_IInputElement = 'System.Windows.IInputElement';
	sC_SysWin_LocalValueEnumerator = 'System.Windows.LocalValueEnumerator';
	sC_SysWin_Point = 'System.Windows.Point';
	sC_SysWin_QueryContinueDragEventArgs = 'System.Windows.QueryContinueDragEventArgs';
	sC_SysWin_Rect = 'System.Windows.Rect';
	sC_SysWin_RequestBringIntoViewEventArgs = 'System.Windows.RequestBringIntoViewEventArgs';
	sC_SysWin_RoutedEvent = 'System.Windows.RoutedEvent';
	sC_SysWin_RoutedEventArgs = 'System.Windows.RoutedEventArgs';
	sC_SysWin_Size = 'System.Windows.Size';
	sC_SysWin_SizeChangedEventArgs = 'System.Windows.SizeChangedEventArgs';
	sC_SysWin_Style = 'System.Windows.Style';
	sC_SysWin_UIElement = 'System.Windows.UIElement';
	sC_SysWinCon_ColumnDefinitionCollection = 'System.Windows.Controls.ColumnDefinitionCollection';
	sC_SysWinCon_ContextMenu = 'System.Windows.Controls.ContextMenu';
	sC_SysWinCon_ContextMenuEventArgs = 'System.Windows.Controls.ContextMenuEventArgs';
	sC_SysWinCon_RowDefinitionCollection = 'System.Windows.Controls.RowDefinitionCollection';
	sC_SysWinCon_ToolTipEventArgs = 'System.Windows.Controls.ToolTipEventArgs';
	sC_SysWinDat_BindingBase = 'System.Windows.Data.BindingBase';
	sC_SysWinDat_BindingExpression = 'System.Windows.Data.BindingExpression';
	sC_SysWinDat_BindingExpressionBase = 'System.Windows.Data.BindingExpressionBase';
	sC_SysWinDat_DataTransferEventArgs = 'System.Windows.Data.DataTransferEventArgs';
	sC_SysWinInp_Cursor = 'System.Windows.Input.Cursor';
	sC_SysWinInp_FocusNavigationDirection = 'System.Windows.Input.FocusNavigationDirection';
	sC_SysWinInp_KeyboardFocusChangedEventArgs = 'System.Windows.Input.KeyboardFocusChangedEventArgs';
	sC_SysWinInp_KeyEventArgs = 'System.Windows.Input.KeyEventArgs';
	sC_SysWinInp_ManipulationBoundaryFeedbackEventArgs = 'System.Windows.Input.ManipulationBoundaryFeedbackEventArgs';
	sC_SysWinInp_ManipulationCompletedEventArgs = 'System.Windows.Input.ManipulationCompletedEventArgs';
	sC_SysWinInp_ManipulationDeltaEventArgs = 'System.Windows.Input.ManipulationDeltaEventArgs';
	sC_SysWinInp_ManipulationInertiaStartingEventArgs = 'System.Windows.Input.ManipulationInertiaStartingEventArgs';
	sC_SysWinInp_ManipulationStartedEventArgs = 'System.Windows.Input.ManipulationStartedEventArgs';
	sC_SysWinInp_ManipulationStartingEventArgs = 'System.Windows.Input.ManipulationStartingEventArgs';
	sC_SysWinInp_MouseButtonEventArgs = 'System.Windows.Input.MouseButtonEventArgs';
	sC_SysWinInp_MouseEventArgs = 'System.Windows.Input.MouseEventArgs';
	sC_SysWinInp_MouseWheelEventArgs = 'System.Windows.Input.MouseWheelEventArgs';
	sC_SysWinInp_QueryCursorEventArgs = 'System.Windows.Input.QueryCursorEventArgs';
	sC_SysWinInp_StylusButtonEventArgs = 'System.Windows.Input.StylusButtonEventArgs';
	sC_SysWinInp_StylusDownEventArgs = 'System.Windows.Input.StylusDownEventArgs';
	sC_SysWinInp_StylusEventArgs = 'System.Windows.Input.StylusEventArgs';
	sC_SysWinInp_StylusSystemGestureEventArgs = 'System.Windows.Input.StylusSystemGestureEventArgs';
	sC_SysWinInp_TextCompositionEventArgs = 'System.Windows.Input.TextCompositionEventArgs';
	sC_SysWinInp_TouchDevice = 'System.Windows.Input.TouchDevice';
	sC_SysWinInp_TouchEventArgs = 'System.Windows.Input.TouchEventArgs';
	sC_SysWinInp_TraversalRequest = 'System.Windows.Input.TraversalRequest';
	sC_SysWinMed_GeneralTransform = 'System.Windows.Media.GeneralTransform';
	sC_SysWinMed_SolidColorBrush = 'System.Windows.Media.SolidColorBrush';
	sC_SysWinMed_Visual = 'System.Windows.Media.Visual';
	sC_SysWinMedAni_AnimationClock = 'System.Windows.Media.Animation.AnimationClock';
	sC_SysWinMedAni_AnimationTimeline = 'System.Windows.Media.Animation.AnimationTimeline';
	sC_SysWinMedAni_HandoffBehavior = 'System.Windows.Media.Animation.HandoffBehavior';
	sC_SysWinMedAni_Storyboard = 'System.Windows.Media.Animation.Storyboard';
	sC_SysWinMedEff_BitmapEffect = 'System.Windows.Media.Effects.BitmapEffect';
	sC_SysWinMedEff_BitmapEffectInput = 'System.Windows.Media.Effects.BitmapEffectInput';
	sC_SysWinMedMed_GeneralTransform2DTo3D = 'System.Windows.Media.Media3D.GeneralTransform2DTo3D';
	sC_SysWinMedMed_Visual3D = 'System.Windows.Media.Media3D.Visual3D';

// **** Delphi Type FullNames ****

	sD_TMyControl1 = 'MyControls.TMyControl1';
	sD_TMyControlEventArgs = 'MyControls.TMyControlEventArgs';
	sD_TMouseEventArgs = 'MyControls.TMouseEventArgs';
	sD_TTouchEventArgs = 'MyControls.TTouchEventArgs';
	sD_TKeyEventArgs = 'MyControls.TKeyEventArgs';
	sD_TManipulationBoundaryFeedbackEventArgs = 'MyControls.TManipulationBoundaryFeedbackEventArgs';
	sD_TManipulationCompletedEventArgs = 'MyControls.TManipulationCompletedEventArgs';
	sD_TManipulationDeltaEventArgs = 'MyControls.TManipulationDeltaEventArgs';
	sD_TManipulationInertiaStartingEventArgs = 'MyControls.TManipulationInertiaStartingEventArgs';
	sD_TManipulationStartedEventArgs = 'MyControls.TManipulationStartedEventArgs';
	sD_TManipulationStartingEventArgs = 'MyControls.TManipulationStartingEventArgs';
	sD_TDataTransferEventArgs = 'MyControls.TDataTransferEventArgs';
	sD_TBitmapEffect = 'MyControls.TBitmapEffect';
	sD_TBitmapEffectInput = 'MyControls.TBitmapEffectInput';
	sD_TColumnDefinitionCollection = 'MyControls.TColumnDefinitionCollection';
	sD_TContextMenu = 'MyControls.TContextMenu';
	sD_TCursor = 'MyControls.TCursor';
	sD_TStyle = 'MyControls.TStyle';
	sD_TSolidColorBrush = 'MyControls.TSolidColorBrush';
	sD_TRowDefinitionCollection = 'MyControls.TRowDefinitionCollection';

implementation
end.

