(*
 * Generated by .Net DLL/WSDL Import Utility for Delphi
 *
 * Version:  6.0.5.1
 *
 * File generated on 09/11/2018 21:46:22 from .Net Library location below.
 *    .Net Library GAC Path: WindowsFormsIntegration
 *
 * Home: https://www.crystalnet-tech.com/RuntimeLibrary/RuntimeLibrary4Delphi
 *)

unit WindowsFormsIntegration.Consts;

interface

const

	sC_WindowsFormsIntegration_Asm_ID = '06d73cb3-1e0f-4725-bc23-ccb82c98ddf4';
	sC_WindowsFormsIntegration_sC_AssemblyPath = 'WindowsFormsIntegration';

	sC_Sys_Boolean = 'System.Boolean';
	sC_Sys_Boolean_2 = 'System.Boolean&';
	sC_Sys_Delegate = 'System.Delegate';
	sC_Sys_EventArgs = 'System.EventArgs';
	sC_Sys_Exception = 'System.Exception';
	sC_Sys_IAsyncResult = 'System.IAsyncResult';
	sC_Sys_Int32 = 'System.Int32';
	sC_Sys_IntPtr = 'System.IntPtr';
	sC_Sys_Object_ = 'System.Object';
	sC_Sys_Object__2 = 'System.Object';
	sC_Sys_ObjectArray = 'System.Object[]';
	sC_Sys_Single = 'System.Single';
	sC_Sys_String_ = 'System.String';
	sC_Sys_Type_ = 'System.Type';
	sC_Sys_Void = 'System.Void';
	sC_SysCom_CancelEventArgs = 'System.ComponentModel.CancelEventArgs';
	sC_SysDra_Bitmap = 'System.Drawing.Bitmap';
	sC_SysDra_Bitmap_2 = 'System.Drawing.Bitmap&';
	sC_SysDra_Graphics = 'System.Drawing.Graphics';
	sC_SysDra_Point = 'System.Drawing.Point';
	sC_SysDra_Rectangle = 'System.Drawing.Rectangle';
	sC_SysDra_Region = 'System.Drawing.Region';
	sC_SysDra_Size = 'System.Drawing.Size';
	sC_SysDra_SizeF = 'System.Drawing.SizeF';
	sC_SysRunRem_ObjRef = 'System.Runtime.Remoting.ObjRef';
	sC_SysWin_DependencyObject = 'System.Windows.DependencyObject';
	sC_SysWin_DependencyProperty = 'System.Windows.DependencyProperty';
	sC_SysWin_DependencyPropertyChangedEventArgs = 'System.Windows.DependencyPropertyChangedEventArgs';
	sC_SysWin_DependencyPropertyKey = 'System.Windows.DependencyPropertyKey';
	sC_SysWin_DpiChangedEventArgs = 'System.Windows.DpiChangedEventArgs';
	sC_SysWin_DragEventArgs = 'System.Windows.DragEventArgs';
	sC_SysWin_EventRoute = 'System.Windows.EventRoute';
	sC_SysWin_GiveFeedbackEventArgs = 'System.Windows.GiveFeedbackEventArgs';
	sC_SysWin_IInputElement = 'System.Windows.IInputElement';
	sC_SysWin_LocalValueEnumerator = 'System.Windows.LocalValueEnumerator';
	sC_SysWin_Point = 'System.Windows.Point';
	sC_SysWin_QueryContinueDragEventArgs = 'System.Windows.QueryContinueDragEventArgs';
	sC_SysWin_Rect = 'System.Windows.Rect';
	sC_SysWin_RequestBringIntoViewEventArgs = 'System.Windows.RequestBringIntoViewEventArgs';
	sC_SysWin_RoutedEvent = 'System.Windows.RoutedEvent';
	sC_SysWin_RoutedEventArgs = 'System.Windows.RoutedEventArgs';
	sC_SysWin_Size = 'System.Windows.Size';
	sC_SysWin_SizeChangedEventArgs = 'System.Windows.SizeChangedEventArgs';
	sC_SysWin_Style = 'System.Windows.Style';
	sC_SysWin_UIElement = 'System.Windows.UIElement';
	sC_SysWin_Window = 'System.Windows.Window';
	sC_SysWinCon_ContextMenu = 'System.Windows.Controls.ContextMenu';
	sC_SysWinCon_ContextMenuEventArgs = 'System.Windows.Controls.ContextMenuEventArgs';
	sC_SysWinCon_Panel = 'System.Windows.Controls.Panel';
	sC_SysWinCon_ToolTipEventArgs = 'System.Windows.Controls.ToolTipEventArgs';
	sC_SysWinDat_BindingBase = 'System.Windows.Data.BindingBase';
	sC_SysWinDat_BindingExpression = 'System.Windows.Data.BindingExpression';
	sC_SysWinDat_BindingExpressionBase = 'System.Windows.Data.BindingExpressionBase';
	sC_SysWinDat_DataTransferEventArgs = 'System.Windows.Data.DataTransferEventArgs';
	sC_SysWinFor_BoundsSpecified = 'System.Windows.Forms.BoundsSpecified';
	sC_SysWinFor_Control = 'System.Windows.Forms.Control';
	sC_SysWinFor_ControlCollection = 'System.Windows.Forms.Control+ControlCollection';
	sC_SysWinFor_ControlEventArgs = 'System.Windows.Forms.ControlEventArgs';
	sC_SysWinFor_DragDropEffects = 'System.Windows.Forms.DragDropEffects';
	sC_SysWinFor_DragEventArgs = 'System.Windows.Forms.DragEventArgs';
	sC_SysWinFor_Form = 'System.Windows.Forms.Form';
	sC_SysWinFor_GetChildAtPointSkip = 'System.Windows.Forms.GetChildAtPointSkip';
	sC_SysWinFor_GiveFeedbackEventArgs = 'System.Windows.Forms.GiveFeedbackEventArgs';
	sC_SysWinFor_HelpEventArgs = 'System.Windows.Forms.HelpEventArgs';
	sC_SysWinFor_IContainerControl = 'System.Windows.Forms.IContainerControl';
	sC_SysWinFor_InvalidateEventArgs = 'System.Windows.Forms.InvalidateEventArgs';
	sC_SysWinFor_KeyEventArgs = 'System.Windows.Forms.KeyEventArgs';
	sC_SysWinFor_KeyPressEventArgs = 'System.Windows.Forms.KeyPressEventArgs';
	sC_SysWinFor_LayoutEventArgs = 'System.Windows.Forms.LayoutEventArgs';
	sC_SysWinFor_Message = 'System.Windows.Forms.Message&';
	sC_SysWinFor_MouseEventArgs = 'System.Windows.Forms.MouseEventArgs';
	sC_SysWinFor_PaintEventArgs = 'System.Windows.Forms.PaintEventArgs';
	sC_SysWinFor_PreProcessControlState = 'System.Windows.Forms.PreProcessControlState';
	sC_SysWinFor_PreviewKeyDownEventArgs = 'System.Windows.Forms.PreviewKeyDownEventArgs';
	sC_SysWinFor_QueryAccessibilityHelpEventArgs = 'System.Windows.Forms.QueryAccessibilityHelpEventArgs';
	sC_SysWinFor_QueryContinueDragEventArgs = 'System.Windows.Forms.QueryContinueDragEventArgs';
	sC_SysWinFor_UICuesEventArgs = 'System.Windows.Forms.UICuesEventArgs';
	sC_SysWinForInt_ChildChangedEventArgs = 'System.Windows.Forms.Integration.ChildChangedEventArgs';
	sC_SysWinForInt_ElementHost = 'System.Windows.Forms.Integration.ElementHost';
	sC_SysWinForInt_IntegrationExceptionEventArgs = 'System.Windows.Forms.Integration.IntegrationExceptionEventArgs';
	sC_SysWinForInt_LayoutExceptionEventArgs = 'System.Windows.Forms.Integration.LayoutExceptionEventArgs';
	sC_SysWinForInt_PropertyMap = 'System.Windows.Forms.Integration.PropertyMap';
	sC_SysWinForInt_PropertyMappingExceptionEventArgs = 'System.Windows.Forms.Integration.PropertyMappingExceptionEventArgs';
	sC_SysWinForInt_PropertyTranslator = 'System.Windows.Forms.Integration.PropertyTranslator';
	sC_SysWinForInt_WindowsFormsHost = 'System.Windows.Forms.Integration.WindowsFormsHost';
	sC_SysWinInp_Cursor = 'System.Windows.Input.Cursor';
	sC_SysWinInp_FocusNavigationDirection = 'System.Windows.Input.FocusNavigationDirection';
	sC_SysWinInp_KeyboardFocusChangedEventArgs = 'System.Windows.Input.KeyboardFocusChangedEventArgs';
	sC_SysWinInp_KeyEventArgs = 'System.Windows.Input.KeyEventArgs';
	sC_SysWinInp_ManipulationBoundaryFeedbackEventArgs = 'System.Windows.Input.ManipulationBoundaryFeedbackEventArgs';
	sC_SysWinInp_ManipulationCompletedEventArgs = 'System.Windows.Input.ManipulationCompletedEventArgs';
	sC_SysWinInp_ManipulationDeltaEventArgs = 'System.Windows.Input.ManipulationDeltaEventArgs';
	sC_SysWinInp_ManipulationInertiaStartingEventArgs = 'System.Windows.Input.ManipulationInertiaStartingEventArgs';
	sC_SysWinInp_ManipulationStartedEventArgs = 'System.Windows.Input.ManipulationStartedEventArgs';
	sC_SysWinInp_ManipulationStartingEventArgs = 'System.Windows.Input.ManipulationStartingEventArgs';
	sC_SysWinInp_MouseButtonEventArgs = 'System.Windows.Input.MouseButtonEventArgs';
	sC_SysWinInp_MouseEventArgs = 'System.Windows.Input.MouseEventArgs';
	sC_SysWinInp_MouseWheelEventArgs = 'System.Windows.Input.MouseWheelEventArgs';
	sC_SysWinInp_QueryCursorEventArgs = 'System.Windows.Input.QueryCursorEventArgs';
	sC_SysWinInp_StylusButtonEventArgs = 'System.Windows.Input.StylusButtonEventArgs';
	sC_SysWinInp_StylusDownEventArgs = 'System.Windows.Input.StylusDownEventArgs';
	sC_SysWinInp_StylusEventArgs = 'System.Windows.Input.StylusEventArgs';
	sC_SysWinInp_StylusSystemGestureEventArgs = 'System.Windows.Input.StylusSystemGestureEventArgs';
	sC_SysWinInp_TextCompositionEventArgs = 'System.Windows.Input.TextCompositionEventArgs';
	sC_SysWinInp_TouchDevice = 'System.Windows.Input.TouchDevice';
	sC_SysWinInp_TouchEventArgs = 'System.Windows.Input.TouchEventArgs';
	sC_SysWinInp_TraversalRequest = 'System.Windows.Input.TraversalRequest';
	sC_SysWinMed_GeneralTransform = 'System.Windows.Media.GeneralTransform';
	sC_SysWinMed_Visual = 'System.Windows.Media.Visual';
	sC_SysWinMedAni_AnimationClock = 'System.Windows.Media.Animation.AnimationClock';
	sC_SysWinMedAni_AnimationTimeline = 'System.Windows.Media.Animation.AnimationTimeline';
	sC_SysWinMedAni_HandoffBehavior = 'System.Windows.Media.Animation.HandoffBehavior';
	sC_SysWinMedAni_Storyboard = 'System.Windows.Media.Animation.Storyboard';
	sC_SysWinMedEff_BitmapEffect = 'System.Windows.Media.Effects.BitmapEffect';
	sC_SysWinMedEff_BitmapEffectInput = 'System.Windows.Media.Effects.BitmapEffectInput';
	sC_SysWinMedMed_GeneralTransform2DTo3D = 'System.Windows.Media.Media3D.GeneralTransform2DTo3D';
	sC_SysWinMedMed_Visual3D = 'System.Windows.Media.Media3D.Visual3D';
	sC_WindowsFormsIntegration_sC_WSDLDomain = 'sC_WindowsFormsIntegration_sC_WSDLDomain';
	sC_WindowsFormsIntegration_sC_WSDLPassword = 'WindowsFormsIntegration';
	sC_WindowsFormsIntegration_sC_WSDLUserName = 'WindowsFormsIntegration';

// **** Delphi Type FullNames ****

	sD_TChildChangedEventArgs = 'WindowsFormsIntegration.TChildChangedEventArgs';
	sD_TElementHost = 'WindowsFormsIntegration.TElementHost';
	sD_TElementHostHelper = 'WindowsFormsIntegration.TElementHostHelper';
	sD_TIntegrationExceptionEventArgs = 'WindowsFormsIntegration.TIntegrationExceptionEventArgs';
	sD_TLayoutExceptionEventArgs = 'WindowsFormsIntegration.TLayoutExceptionEventArgs';
	sD_TPropertyMap = 'WindowsFormsIntegration.TPropertyMap';
	sD_TPropertyMappingExceptionEventArgs = 'WindowsFormsIntegration.TPropertyMappingExceptionEventArgs';
	sD_TWindowsFormsHost = 'WindowsFormsIntegration.TWindowsFormsHost';
	sD_TWindowsFormsHostHelper = 'WindowsFormsIntegration.TWindowsFormsHostHelper';
	sD_TDragEventArgs = 'WindowsFormsIntegration.TDragEventArgs';
	sD_TGiveFeedbackEventArgs = 'WindowsFormsIntegration.TGiveFeedbackEventArgs';
	sD_TQueryContinueDragEventArgs = 'WindowsFormsIntegration.TQueryContinueDragEventArgs';
	sD_TControlCollection = 'WindowsFormsIntegration.TControlCollection';
	sD_TPanel = 'WindowsFormsIntegration.TPanel';
	sD_TWindow = 'WindowsFormsIntegration.TWindow';
	sD_TPropertyTranslator = 'WindowsFormsIntegration.TPropertyTranslator';
	sD_TDpiChangedEventArgs = 'WindowsFormsIntegration.TDpiChangedEventArgs';
	sD_TMouseEventArgs = 'WindowsFormsIntegration.TMouseEventArgs';
	sD_TTouchEventArgs = 'WindowsFormsIntegration.TTouchEventArgs';
	sD_TKeyEventArgs = 'WindowsFormsIntegration.TKeyEventArgs';
	sD_TManipulationBoundaryFeedbackEventArgs = 'WindowsFormsIntegration.TManipulationBoundaryFeedbackEventArgs';
	sD_TManipulationCompletedEventArgs = 'WindowsFormsIntegration.TManipulationCompletedEventArgs';
	sD_TManipulationDeltaEventArgs = 'WindowsFormsIntegration.TManipulationDeltaEventArgs';
	sD_TManipulationInertiaStartingEventArgs = 'WindowsFormsIntegration.TManipulationInertiaStartingEventArgs';
	sD_TManipulationStartedEventArgs = 'WindowsFormsIntegration.TManipulationStartedEventArgs';
	sD_TManipulationStartingEventArgs = 'WindowsFormsIntegration.TManipulationStartingEventArgs';
	sD_TDataTransferEventArgs = 'WindowsFormsIntegration.TDataTransferEventArgs';
	sD_TBitmapEffect = 'WindowsFormsIntegration.TBitmapEffect';
	sD_TBitmapEffectInput = 'WindowsFormsIntegration.TBitmapEffectInput';
	sD_TContextMenu = 'WindowsFormsIntegration.TContextMenu';
	sD_TCursor = 'WindowsFormsIntegration.TCursor';
	sD_TStyle = 'WindowsFormsIntegration.TStyle';

implementation
end.

